// Code generated by test-engine skill on 2026-07-09
// Issue: #3 — API — Create & Board
// Blast radius tier: 2
// Auto-generated: 5 tests
// Interview-generated: 18 tests
// Total: 23 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// See setup_test.go for the methodology note on real-server vs.
// ResponseRecorder usage.
//
// Review-pass fix applied (2026-07-09, before commit): removed
// TestCreateBookmark_TimestampsAreRFC3339UTC — TZ-dependent (the fake's
// clock defaults to bare time.Now, so CreatedAt carries a local offset on
// any non-UTC machine, only passing in CI's UTC runner), and misplaced —
// UTC timestamps are the adapter's guarantee, already tested in #2.
//
// Required exported surface this file locks (see issue #3 body):
//   func api.NewRouter(repo adapter.BookmarkRepository) http.Handler

package api_test

import (
	"bytes"
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"trailhead/internal/api"
	"trailhead/internal/domain"
)

// --- Happy path (Acceptance Criteria) ---------------------------------

// auto: acceptance criteria
func TestCreateBookmark_Returns201WithFullBody(t *testing.T) {
	srv, _ := newTestServer(t)

	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/blog/my-great-post"}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusCreated, resp.StatusCode)

	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, domain.CanonicalURL("https://example.com/blog/my-great-post"), got.CanonicalURL)
	assert.Equal(t, "example.com - My Great Post", got.Title)
	assert.Equal(t, domain.StatusInbox, got.Status)
	assert.NotEmpty(t, got.ID)
}

// auto: acceptance criteria
// from interview: Q9
func TestCreateBookmark_RetrievableViaBoardImmediatelyAfter(t *testing.T) {
	srv, _ := newTestServer(t)

	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a"}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var created domain.Bookmark
	decodeJSON(t, resp, &created)

	boardResp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	assertJSONContentType(t, boardResp)
	require.Equal(t, http.StatusOK, boardResp.StatusCode)

	var board domain.Board
	decodeJSON(t, boardResp, &board)

	found := false
	for _, b := range board.Inbox {
		if b.ID == created.ID {
			found = true
			break
		}
	}
	assert.True(t, found, "created bookmark must appear in board.inbox immediately after — catches wiring/persistence bugs the isolated tests miss")
}

// auto: acceptance criteria
func TestCreateBookmark_Duplicate_Returns409WithExisting(t *testing.T) {
	srv, _ := newTestServer(t)

	firstResp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a"}`))
	require.NoError(t, err)
	var first domain.Bookmark
	decodeJSON(t, firstResp, &first)

	secondResp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a"}`))
	require.NoError(t, err)
	assertJSONContentType(t, secondResp)
	assert.Equal(t, http.StatusConflict, secondResp.StatusCode)

	var body struct {
		Error    string          `json:"error"`
		Existing domain.Bookmark `json:"existing"`
	}
	decodeJSON(t, secondResp, &body)
	assert.Equal(t, "duplicate", body.Error)
	// from interview: Q6 — the 409 body must carry the ACTUAL stored
	// bookmark, not a zero-value or wrong one.
	assert.Equal(t, first.ID, body.Existing.ID, "409 body must contain the actually-stored bookmark, not a zero-value or wrong one")
}

// auto: acceptance criteria
func TestCreateBookmark_InvalidURL_Returns400(t *testing.T) {
	srv, _ := newTestServer(t)

	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "ftp://not-http-or-https"}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)

	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "invalid_url", body.Error)

	boardResp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	var board domain.Board
	decodeJSON(t, boardResp, &board)
	count := len(board.Inbox) + len(board.Reading) + len(board.Done)
	assert.Zero(t, count, "no bookmark should be created for an invalid URL")
}

// TestCreateBookmark_InvalidURL_MessageDoesNotLeakSubmittedURL is
// Trailhead's own scar (H-12 / #2's redaction) applied one layer up: the
// handler must not re-introduce the submitted URL when composing its
// invalid_url message, even though the adapter's own error is redacted.
// from interview: Q7
func TestCreateBookmark_InvalidURL_MessageDoesNotLeakSubmittedURL(t *testing.T) {
	srv, _ := newTestServer(t)
	const submitted = "ftp://totally-distinctive-marker-string"

	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "`+submitted+`"}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusBadRequest, resp.StatusCode)

	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.NotContains(t, body.Message, submitted, "invalid_url message must not echo the submitted URL")
	assert.NotContains(t, body.Message, "totally-distinctive-marker-string")
}

// --- Request validation: bad_request (interview Q2, Q10) --------------

func TestCreateBookmark_MissingURL_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{"title": "x"}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

func TestCreateBookmark_NonStringURL_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{"url": 123}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// TestCreateBookmark_EmptyStringURL_Returns400BadRequest — empty url is
// treated as missing, NOT as invalid_url. See Wire Contract.
func TestCreateBookmark_EmptyStringURL_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{"url": ""}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error, "empty-string url must be bad_request, not invalid_url")
}

func TestCreateBookmark_UnparseableJSON_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{not valid json`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// TestCreateBookmark_UnknownField_Returns400BadRequest proves strict
// DisallowUnknownFields decoding catches client typos.
func TestCreateBookmark_UnknownField_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a", "urll": "typo"}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// TestCreateBookmark_TagsInRequestBody_Returns400BadRequest: tags is
// intentionally not part of the create request schema (deferred to
// Update) — sending it is an unknown field, not silently ignored.
// from interview: Q1, Q2
func TestCreateBookmark_TagsInRequestBody_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a", "tags": ["go"]}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode, "tags is not settable on create — sending it must be rejected as an unknown field, not silently accepted or ignored")
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// --- Title semantics (interview Q1) ------------------------------------

func TestCreateBookmark_NullTitle_DefaultsViaDefaultTitle(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/blog/my-great-post", "title": null}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, "example.com - My Great Post", got.Title)
}

// TestCreateBookmark_EmptyStringTitle_StoredAsExplicitEmpty: "" is
// explicit-empty, distinct from null-means-default.
func TestCreateBookmark_EmptyStringTitle_StoredAsExplicitEmpty(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a", "title": ""}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, "", got.Title, `an explicit "" title must be stored as empty, not defaulted via DefaultTitle`)
}

func TestCreateBookmark_NonStringTitle_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a", "title": 123}`))
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// TestCreateBookmark_UnicodeTitle_RoundTrips is a cheap-optional case
// per interview Q9.
func TestCreateBookmark_UnicodeTitle_RoundTrips(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a", "title": "日本語タイトル 🎉"}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, "日本語タイトル 🎉", got.Title)
}

// --- Body size cap (interview Q10) --------------------------------------

// TestCreateBookmark_OversizedBody_Returns413PayloadTooLarge: cap is
// 16 KiB (16384 bytes), applied before decode, POST only.
// from interview: Q10
func TestCreateBookmark_OversizedBody_Returns413PayloadTooLarge(t *testing.T) {
	srv, _ := newTestServer(t)

	// A syntactically valid but oversized body: pad the title well past
	// 16 KiB so the cap trips regardless of exact framing overhead.
	oversizedTitle := strings.Repeat("a", 20000)
	body := `{"url": "https://example.com/a", "title": "` + oversizedTitle + `"}`

	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(body))
	require.NoError(t, err)
	assert.Equal(t, http.StatusRequestEntityTooLarge, resp.StatusCode)

	var errBody errorEnvelope
	decodeJSON(t, resp, &errBody)
	assert.Equal(t, "payload_too_large", errBody.Error)
}

// --- Optional-field serialization (interview Q7 — Islamic Chatbot scar) -

// TestCreateBookmark_NilAuthorAndFinishedAt_SerializeAsNull guards
// against an omitempty (or custom marshaler) silently dropping these
// keys — the client must be able to distinguish "absent" from "not sent."
// from interview: Q7
func TestCreateBookmark_NilAuthorAndFinishedAt_SerializeAsNull(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json",
		strings.NewReader(`{"url": "https://example.com/a"}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var buf bytes.Buffer
	_, err = buf.ReadFrom(resp.Body)
	require.NoError(t, err)
	defer resp.Body.Close()

	raw := buf.String()
	assert.Contains(t, raw, `"author":null`, "author must render as explicit null, never omitted")
	assert.Contains(t, raw, `"finished_at":null`, "finished_at must render as explicit null, never omitted")
}

// --- Board (Acceptance Criteria + interview Q1) -------------------------

// auto: acceptance criteria
func TestBoard_Returns200WithGroupedBookmarks(t *testing.T) {
	srv, _ := newTestServer(t)

	_, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{"url": "https://example.com/1"}`))
	require.NoError(t, err)
	_, err = http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{"url": "https://example.com/2"}`))
	require.NoError(t, err)

	resp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusOK, resp.StatusCode)

	var board domain.Board
	decodeJSON(t, resp, &board)
	assert.Len(t, board.Inbox, 2)
	assert.Empty(t, board.Reading)
	assert.Empty(t, board.Done)
}

// TestBoard_EmptyRepo_ReturnsThreeEmptyArraysNotNull checks the raw wire
// bytes, not just the decoded Go value — decoding null into a slice field
// can produce the same Go nil a decoded [] would in some paths, so
// asserting on decoded board.Inbox alone wouldn't reliably catch a
// null-instead-of-[] regression the way checking the raw JSON text does.
func TestBoard_EmptyRepo_ReturnsThreeEmptyArraysNotNull(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	require.Equal(t, http.StatusOK, resp.StatusCode)

	var buf bytes.Buffer
	_, err = buf.ReadFrom(resp.Body)
	require.NoError(t, err)
	defer resp.Body.Close()

	raw := buf.String()
	assert.Contains(t, raw, `"inbox":[]`)
	assert.Contains(t, raw, `"reading":[]`)
	assert.Contains(t, raw, `"done":[]`)
	assert.NotContains(t, raw, `"inbox":null`)
	assert.NotContains(t, raw, `"reading":null`)
	assert.NotContains(t, raw, `"done":null`)
}

// --- Routing conventions (interview Q4) ---------------------------------

func TestUnknownPath_Returns404NotFound(t *testing.T) {
	srv, _ := newTestServer(t)
	resp, err := http.Get(srv.URL + "/api/does-not-exist")
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusNotFound, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "not_found", body.Error)
}

func TestKnownPath_WrongMethod_Returns405MethodNotAllowed(t *testing.T) {
	srv, _ := newTestServer(t)
	req, err := http.NewRequest(http.MethodDelete, srv.URL+"/api/bookmarks", nil)
	require.NoError(t, err)
	resp, err := http.DefaultClient.Do(req)
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusMethodNotAllowed, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "method_not_allowed", body.Error)
}

// --- Infra failure paths (interview Q3, Q4, Q6) -------------------------
//
// These two use httptest.NewRecorder() + router.ServeHTTP directly,
// deliberately bypassing the live server — see setup_test.go's
// methodology note.

// from interview: Q3, Q6
func TestCreateBookmark_ContextCanceled_Returns500Internal(t *testing.T) {
	repo := newFakeRepoForRecorder(t)
	router := api.NewRouter(repo)

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	req := httptest.NewRequest(http.MethodPost, "/api/bookmarks", strings.NewReader(`{"url": "https://example.com/a"}`))
	req = req.WithContext(ctx)
	rec := httptest.NewRecorder()

	router.ServeHTTP(rec, req)

	assert.Equal(t, http.StatusInternalServerError, rec.Code)
	assert.Equal(t, "application/json", rec.Header().Get("Content-Type"))

	var body errorEnvelope
	require.NoError(t, decodeRecorderJSON(rec, &body))
	assert.Equal(t, "internal", body.Error)
	// from interview: Q3 — constant generic message, never the wrapped error.
	assert.Equal(t, "internal server error", body.Message)
}

// from interview: Q4, Q6
func TestBoard_ContextCanceled_Returns500Internal(t *testing.T) {
	repo := newFakeRepoForRecorder(t)
	router := api.NewRouter(repo)

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	req := httptest.NewRequest(http.MethodGet, "/api/board", nil)
	req = req.WithContext(ctx)
	rec := httptest.NewRecorder()

	router.ServeHTTP(rec, req)

	assert.Equal(t, http.StatusInternalServerError, rec.Code)
	var body errorEnvelope
	require.NoError(t, decodeRecorderJSON(rec, &body))
	assert.Equal(t, "internal", body.Error)
	assert.Equal(t, "internal server error", body.Message)
}
