// Code generated by test-engine skill on 2026-07-22
// Issue: #5 — API — Move route
// Blast radius tier: 2
// Auto-generated: 2 tests
// Interview-generated: 21 tests
// Total: 23 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// See setup_test.go (issue #3) for newTestServer / newFakeRepoForRecorder /
// decodeJSON / decodeRecorderJSON / assertJSONContentType / errorEnvelope —
// all reused as-is, no additions needed for this issue.
//
// Wire Contract: CONFIRMED by developer, 2026-07-22 — see
// docs/issues/05-api-move.md for the full locked contract, including two
// amendments made during this interview beyond the issue body's original
// text: (1) before/after are UUID-format-gated (not purely opaque) to
// close a fake-vs-real divergence — a non-UUID string would 22P02 against
// real Postgres but no-op-fallback against FakeBookmarkRepository; (2) a
// malformed {id} path param resolves to 404, not 400, collapsed with the
// "does not exist" case (distinct role: {id} is the resource address,
// before/after are request fields).
//
// Phase 1 finding: FakeBookmarkRepository.Move (internal/testutil) is
// already fully implemented, not a stub — traced against DECISIONS.md and
// ports.go and found correct (Before wins/After ignored unconditionally,
// all three fallback triggers collapse to end-of-column via the same
// pre-search removal mechanism, Done<->Done falls through the switch and
// preserves FinishedAt, UpdatedAt bumps unconditionally, NotFound checked
// before any mutation). No fake changes were needed for this issue.
//
// Required exported surface this file locks: none beyond what issue #3
// already locked (api.NewRouter) — this issue adds no new exported api
// package surface, only a new route within NewRouter and (per issue #5's
// own Wire Contract) domain.Status.IsValid() bool, which this file
// exercises only through HTTP behavior, never calling it directly.

package api_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"trailhead/internal/api"
	"trailhead/internal/domain"
)

// createBookmarkViaAPI seeds fixture data through the real Create
// endpoint, not by touching the fake directly — mirrors #3's black-box
// discipline (see TestCreateBookmark_RetrievableViaBoardImmediatelyAfter).
func createBookmarkViaAPI(t *testing.T, srv *httptest.Server, url string) domain.Bookmark {
	t.Helper()
	resp, err := http.Post(srv.URL+"/api/bookmarks", "application/json", strings.NewReader(`{"url": "`+url+`"}`))
	require.NoError(t, err)
	require.Equal(t, http.StatusCreated, resp.StatusCode)
	var b domain.Bookmark
	decodeJSON(t, resp, &b)
	return b
}

// moveBookmark POSTs to /api/bookmarks/{id}/move. id is a plain string,
// not domain.BookmarkID, so malformed-id tests can pass arbitrary values.
func moveBookmark(t *testing.T, srv *httptest.Server, id, body string) *http.Response {
	t.Helper()
	resp, err := http.Post(srv.URL+"/api/bookmarks/"+id+"/move", "application/json", strings.NewReader(body))
	require.NoError(t, err)
	return resp
}

// --- Happy path (Acceptance Criteria) -----------------------------------

// auto: acceptance criteria
func TestMoveBookmark_ValidRequest_Returns200WithUpdatedBookmark(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusOK, resp.StatusCode)

	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, created.ID, got.ID)
	assert.Equal(t, domain.StatusReading, got.Status)
	assert.Nil(t, got.FinishedAt)
}

// auto: acceptance criteria
func TestMoveBookmark_UnknownID_Returns404NotFound(t *testing.T) {
	srv, _ := newTestServer(t)
	const wellFormedUnknown = "11111111-1111-1111-1111-111111111111"

	resp := moveBookmark(t, srv, wellFormedUnknown, `{"target_status": "reading"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusNotFound, resp.StatusCode)

	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "not_found", body.Error)
}

// --- target_status validation (interview Q1) ----------------------------

// from interview: Q1 — mirrors #3's url treatment: missing is bad_request
// via the required-field path, checked before IsValid().
func TestMoveBookmark_MissingTargetStatus_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// from interview: Q1
func TestMoveBookmark_NonStringTargetStatus_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": 123}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// from interview: Q1 — empty is treated as missing, same required-field
// path, NOT fed into IsValid().
func TestMoveBookmark_EmptyStringTargetStatus_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": ""}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error, `empty-string target_status must be bad_request via the required-field path, not the IsValid() path`)
}

// from interview: Q1 — present but unrecognized goes through IsValid(), a
// distinct code path from the required-field check above.
func TestMoveBookmark_UnrecognizedTargetStatus_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "archived"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// from interview: Q1 — proves missing and unrecognized are genuinely
// distinct code paths, not the same generic message reused for both.
// Wording itself is not locked (Dispatch's choice), only distinctness.
func TestMoveBookmark_MissingVsUnrecognizedTargetStatus_DistinctMessages(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	missingResp := moveBookmark(t, srv, string(created.ID), `{}`)
	var missingBody errorEnvelope
	decodeJSON(t, missingResp, &missingBody)

	unrecognizedResp := moveBookmark(t, srv, string(created.ID), `{"target_status": "archived"}`)
	var unrecognizedBody errorEnvelope
	decodeJSON(t, unrecognizedResp, &unrecognizedBody)

	assert.NotEqual(t, missingBody.Message, unrecognizedBody.Message,
		"missing and unrecognized target_status must be distinguishable messages, not the same generic text reused for both")
}

// --- before/after: opaque pass-through + UUID-format gate (Q2, Q3) ------

// from interview: Q2/Q3 — omitted keys (the natural REST-client shape,
// not explicit null) must behave identically to null: no neighbor
// constraint, end-of-column.
func TestMoveBookmark_NoBeforeAfterKeys_EndOfColumn(t *testing.T) {
	srv, _ := newTestServer(t)
	first := createBookmarkViaAPI(t, srv, "https://example.com/1")
	second := createBookmarkViaAPI(t, srv, "https://example.com/2")

	resp1 := moveBookmark(t, srv, string(first.ID), `{"target_status": "reading"}`)
	require.Equal(t, http.StatusOK, resp1.StatusCode)
	resp2 := moveBookmark(t, srv, string(second.ID), `{"target_status": "reading"}`)
	require.Equal(t, http.StatusOK, resp2.StatusCode)

	boardResp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	var board domain.Board
	decodeJSON(t, boardResp, &board)
	require.Len(t, board.Reading, 2)
	assert.Equal(t, first.ID, board.Reading[0].ID, "first move (before/after omitted) lands at end-of-column")
	assert.Equal(t, second.ID, board.Reading[1].ID, "second move also lands at end, after the first")
}

// from interview: Q2 — a real, valid neighbor is honored: Before wins,
// the moved card lands immediately before it (ports.go's locked Move
// contract, exercised end-to-end through the handler).
func TestMoveBookmark_ValidBeforeNeighbor_PlacedBeforeIt(t *testing.T) {
	srv, _ := newTestServer(t)
	anchor := createBookmarkViaAPI(t, srv, "https://example.com/anchor")
	moving := createBookmarkViaAPI(t, srv, "https://example.com/moving")

	anchorResp := moveBookmark(t, srv, string(anchor.ID), `{"target_status": "reading"}`)
	require.Equal(t, http.StatusOK, anchorResp.StatusCode)

	resp := moveBookmark(t, srv, string(moving.ID), `{"target_status": "reading", "before": "`+string(anchor.ID)+`"}`)
	require.Equal(t, http.StatusOK, resp.StatusCode)

	boardResp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	var board domain.Board
	decodeJSON(t, boardResp, &board)
	require.Len(t, board.Reading, 2)
	assert.Equal(t, moving.ID, board.Reading[0].ID, "moving must land immediately before the anchor")
	assert.Equal(t, anchor.ID, board.Reading[1].ID)
}

// from interview: Q2 — the core locked decision: a well-formed but
// nonexistent neighbor id is NOT a 400. It's opaque to the API layer for
// existence purposes and delegated straight to Move's fallback.
func TestMoveBookmark_WellFormedNonexistentNeighbor_FallsBackEndOfColumn_Returns200(t *testing.T) {
	srv, _ := newTestServer(t)
	existing := createBookmarkViaAPI(t, srv, "https://example.com/existing")
	moving := createBookmarkViaAPI(t, srv, "https://example.com/moving")

	existingResp := moveBookmark(t, srv, string(existing.ID), `{"target_status": "reading"}`)
	require.Equal(t, http.StatusOK, existingResp.StatusCode)

	const wellFormedNonexistent = "99999999-9999-9999-9999-999999999999"
	resp := moveBookmark(t, srv, string(moving.ID), `{"target_status": "reading", "before": "`+wellFormedNonexistent+`"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusOK, resp.StatusCode, "a well-formed but nonexistent neighbor id must NOT be a 400 — opaque to the API layer, delegated to Move's fallback")

	boardResp, err := http.Get(srv.URL + "/api/board")
	require.NoError(t, err)
	var board domain.Board
	decodeJSON(t, boardResp, &board)
	require.Len(t, board.Reading, 2)
	assert.Equal(t, existing.ID, board.Reading[0].ID)
	assert.Equal(t, moving.ID, board.Reading[1].ID, "falls back to end-of-column")
}

// from interview: Q3 — the fake-vs-real uuid-cast divergence guard: an
// empty-string before must be rejected at the API boundary, never passed
// through to Move (which would 22P02 against real Postgres).
func TestMoveBookmark_EmptyStringBefore_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading", "before": ""}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// from interview: Q3
func TestMoveBookmark_MalformedBefore_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading", "before": "not-a-uuid"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// from interview: Q3 — proves the UUID-format gate applies to After too,
// not just Before.
func TestMoveBookmark_MalformedAfter_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading", "after": "not-a-uuid"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// --- {id} path param (interview Q4) --------------------------------------

// from interview: Q4 — malformed {id} collapses with "does not exist" ->
// 404, not 400 (distinct role from before/after: {id} is the resource
// address; unresolvable -> 404. before/after are request fields;
// malformed -> 400). Also the uuid-cast fake-vs-real divergence guard,
// one layer up from Q3.
func TestMoveBookmark_MalformedID_Returns404NotFound(t *testing.T) {
	srv, _ := newTestServer(t)

	resp := moveBookmark(t, srv, "not-a-uuid", `{"target_status": "reading"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusNotFound, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "not_found", body.Error)
}

// --- Response finished_at (interview Q5) ----------------------------------

// from interview: Q5 — Move-specific: response finished_at is a non-null
// timestamp on transition into Done. Not a re-test of #3's generic
// null-serialization invariant — this is Move's own behavior.
func TestMoveBookmark_IntoDone_ResponseFinishedAtIsNonNullTimestamp(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "done"}`)
	require.Equal(t, http.StatusOK, resp.StatusCode)

	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, domain.StatusDone, got.Status)
	require.NotNil(t, got.FinishedAt, "finished_at must be a non-null timestamp on transition into Done")
	assert.False(t, got.FinishedAt.IsZero())
}

// from interview: Q5 — Move-specific: response finished_at is explicit
// null on transition out of Done.
func TestMoveBookmark_OutOfDone_ResponseFinishedAtIsNull(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	doneResp := moveBookmark(t, srv, string(created.ID), `{"target_status": "done"}`)
	require.Equal(t, http.StatusOK, doneResp.StatusCode)

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading"}`)
	require.Equal(t, http.StatusOK, resp.StatusCode)

	var got domain.Bookmark
	decodeJSON(t, resp, &got)
	assert.Equal(t, domain.StatusReading, got.Status)
	assert.Nil(t, got.FinishedAt, "finished_at must be cleared to null on transition out of Done")
}

// --- Redaction scar (interview Q7 — the #2/#3 precedent) ------------------
//
// These two use httptest.NewRecorder() + router.ServeHTTP directly,
// deliberately bypassing the live server — see setup_test.go's
// methodology note (a client-canceled context aborts the request before
// the server-side handler runs, making checkContext's server-side path
// un-exercisable through a live round-trip).

// from interview: Q7 — the 500 fallthrough must be the exact constant
// envelope, never the wrapped Move error (which could carry pg text, a
// 22P02-echoed bad value, etc.).
func TestMoveBookmark_ContextCanceled_Returns500Internal_GenericMessage(t *testing.T) {
	repo := newFakeRepoForRecorder(t)
	router := api.NewRouter(repo)

	created, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	req := httptest.NewRequest(http.MethodPost, "/api/bookmarks/"+string(created.ID)+"/move", strings.NewReader(`{"target_status": "reading"}`))
	req = req.WithContext(ctx)
	rec := httptest.NewRecorder()

	router.ServeHTTP(rec, req)

	assert.Equal(t, http.StatusInternalServerError, rec.Code)
	assert.Equal(t, "application/json", rec.Header().Get("Content-Type"))
	var body errorEnvelope
	require.NoError(t, decodeRecorderJSON(rec, &body))
	assert.Equal(t, "internal", body.Error)
	assert.Equal(t, "internal server error", body.Message, "must be the constant generic message, never the wrapped Move error")
}

// from interview: Q7 — a malformed {id} must not echo the submitted value
// back in the error message.
func TestMoveBookmark_MalformedIDMessage_DoesNotEchoSubmittedID(t *testing.T) {
	srv, _ := newTestServer(t)
	const submitted = "totally-distinctive-marker-id"

	resp := moveBookmark(t, srv, submitted, `{"target_status": "reading"}`)
	require.Equal(t, http.StatusNotFound, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.NotContains(t, body.Message, submitted, "not_found message must not echo the submitted id")
}

// from interview: Q7 — a malformed before must not echo the submitted
// value back in the error message.
func TestMoveBookmark_MalformedBeforeMessage_DoesNotEchoSubmittedValue(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")
	const submitted = "totally-distinctive-marker-before"

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading", "before": "`+submitted+`"}`)
	require.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.NotContains(t, body.Message, submitted, "bad_request message must not echo the submitted before value")
}

// --- Routing conventions --------------------------------------------------

// Route-specific wrong-method check applied to this new route — the
// router-level MethodNotAllowed handler is shared (proven generically by
// #3's TestKnownPath_WrongMethod_Returns405MethodNotAllowed), but this
// proves chi's per-route method registration for THIS route also 405s.
func TestMoveBookmark_WrongMethod_Returns405MethodNotAllowed(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	req, err := http.NewRequest(http.MethodGet, srv.URL+"/api/bookmarks/"+string(created.ID)+"/move", nil)
	require.NoError(t, err)
	resp, err := http.DefaultClient.Do(req)
	require.NoError(t, err)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusMethodNotAllowed, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "method_not_allowed", body.Error)
}

// --- Body size cap and decode failures (mirrors #3's pattern) ------------

func TestMoveBookmark_OversizedBody_Returns413PayloadTooLarge(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	oversizedBefore := strings.Repeat("a", 20000)
	body := `{"target_status": "reading", "before": "` + oversizedBefore + `"}`

	resp := moveBookmark(t, srv, string(created.ID), body)
	assert.Equal(t, http.StatusRequestEntityTooLarge, resp.StatusCode)
	var errBody errorEnvelope
	decodeJSON(t, resp, &errBody)
	assert.Equal(t, "payload_too_large", errBody.Error)
}

func TestMoveBookmark_UnparseableJSON_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{not valid json`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}

// TestMoveBookmark_UnknownField_Returns400BadRequest proves strict
// DisallowUnknownFields decoding catches client typos, same as #3.
func TestMoveBookmark_UnknownField_Returns400BadRequest(t *testing.T) {
	srv, _ := newTestServer(t)
	created := createBookmarkViaAPI(t, srv, "https://example.com/a")

	resp := moveBookmark(t, srv, string(created.ID), `{"target_status": "reading", "targett_status": "typo"}`)
	assertJSONContentType(t, resp)
	assert.Equal(t, http.StatusBadRequest, resp.StatusCode)
	var body errorEnvelope
	decodeJSON(t, resp, &body)
	assert.Equal(t, "bad_request", body.Error)
}
