// Code generated by test-engine skill on 2026-07-09
// Issue: #3 — API — Create & Board
// Blast radius tier: 2
// Shared test setup — not itself a test file.
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
//
// Methodology note: this suite uses a real httptest.Server + http.Client
// for most tests, NOT httptest.NewRecorder(), specifically because
// ResponseRecorder does not enforce wire-level header-ordering semantics
// (Content-Type must be set before WriteHeader) — see interview Q6. The
// two context-cancellation tests are the deliberate exception: they use
// ResponseRecorder + router.ServeHTTP directly, since a client-canceled
// context aborts the request before the server-side handler runs, making
// checkContext's server-side path un-exercisable through a live round-trip.

package api_test

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"trailhead/internal/testutil"

	"trailhead/internal/api"
)

// newTestServer wires api.NewRouter over a fresh FakeBookmarkRepository
// and returns a live httptest.Server plus the fake for setup/assertions.
func newTestServer(t *testing.T) (*httptest.Server, *testutil.FakeBookmarkRepository) {
	t.Helper()
	repo := testutil.NewFakeBookmarkRepository()
	router := api.NewRouter(repo)
	srv := httptest.NewServer(router)
	t.Cleanup(srv.Close)
	return srv, repo
}

// newFakeRepoForRecorder returns a fresh fake for the two
// ResponseRecorder-based tests that need direct control over the
// request's context (see the methodology note above).
func newFakeRepoForRecorder(t *testing.T) *testutil.FakeBookmarkRepository {
	t.Helper()
	return testutil.NewFakeBookmarkRepository()
}

// decodeJSON decodes resp.Body into v, failing the test on any error.
func decodeJSON(t *testing.T, resp *http.Response, v interface{}) {
	t.Helper()
	defer resp.Body.Close()
	if err := json.NewDecoder(resp.Body).Decode(v); err != nil {
		t.Fatalf("decodeJSON: %v", err)
	}
}

// decodeRecorderJSON decodes an httptest.ResponseRecorder's body into v.
func decodeRecorderJSON(rec *httptest.ResponseRecorder, v interface{}) error {
	return json.Unmarshal(rec.Body.Bytes(), v)
}

// assertJSONContentType fails the test unless resp carries
// Content-Type: application/json — see interview Q5 ("asserted in tests").
func assertJSONContentType(t *testing.T, resp *http.Response) {
	t.Helper()
	got := resp.Header.Get("Content-Type")
	if got != "application/json" && got != "application/json; charset=utf-8" {
		t.Errorf("Content-Type = %q, want application/json", got)
	}
}

// errorEnvelope matches the locked {"error": string, "message": string} shape.
type errorEnvelope struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}
