// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 6 tests
// Interview-generated: 3 tests
// Total: 9 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Amended 2026-08-07 (developer correction, pre-commit — issue #7 root
// cause): before/after direction was backwards relative to the REAL
// Postgres adapter (which Playwright and production run against).
// Verified against internal/adapter/postgres/repository.go's
// resolveNeighborBounds (Before's bounds are (pos, succ) — the moved card
// lands between Before and Before's own successor, i.e. immediately
// AFTER Before) and tests/integration/postgres/move_test.go's own comment
// ("Before=cardB says 'insert right after B, before C'"). The FAKE
// (FakeBookmarkRepository.Move) has this inverted — tracked separately as
// issue #7 — this file was originally built to the fake's (wrong) side;
// every expectation below is corrected to the real-adapter/ports.go
// semantic. No other file in this session was affected — see the
// developer's correction message for the full grep sweep confirming
// App.test.tsx and web/e2e/*.spec.ts never encoded a before/after
// direction assumption.
//
// Locks the DnD -> API mapping half of the UI Contract in
// docs/issues/06-frontend-board-add-bar.md: how a drop position in a
// column becomes the `before`/`after` neighbor ids sent to
// POST /api/bookmarks/{id}/move (docs/issues/05-api-move.md "Wire
// Contract"). deriveNeighbors is a pure function so this mapping is
// lockable at the fast Vitest layer — Playwright (web/e2e/) covers the
// real pointer/keyboard drag that produces the dropIndex this function
// consumes.
//
// Contract: `targetColumnIds` is the target column's bookmark id array
// with the dragged bookmark already removed by the caller (the "resulting
// order" neighbors) — dnd-kit's `arrayMove`/`over` handling is the
// caller's job, not this function's. `dropIndex` is the 0-based index the
// dragged card should land at; out-of-range values clamp into
// [0, targetColumnIds.length]. `before` is the PREDECESSOR of the drop
// position (the id the moved card lands immediately AFTER — the id
// currently at `dropIndex - 1`); `after` is the SUCCESSOR (the id the
// moved card lands immediately BEFORE — the id currently at `dropIndex`).
// `before` wins over `after` per the Move Wire Contract ("Before wins;
// null = end-of-column") — this function returns both neighbors
// bracketing the drop position so a normal drop never needs to rely on
// Move's stale/cross-status fallback at all; that fallback exists for
// concurrent-edit edge cases, not the common path.

import { describe, expect, it } from 'vitest';

import { deriveNeighbors } from './deriveNeighbors';

describe('deriveNeighbors', () => {
  // --- Auto-generated: DnD -> API mapping (UI Contract) ---

  it('drop in the middle of a column returns the id immediately preceding dropIndex as before, and the id at dropIndex as after', () => {
    expect(deriveNeighbors(['a', 'b', 'c'], 1)).toEqual({ before: 'a', after: 'b' });
  });

  it('drop at index 0 (front of column) returns null before, and the current first id as after', () => {
    expect(deriveNeighbors(['a', 'b', 'c'], 0)).toEqual({ before: null, after: 'a' });
  });

  it('drop at the end of a non-empty column returns the current last id as before, and null after', () => {
    expect(deriveNeighbors(['a', 'b', 'c'], 3)).toEqual({ before: 'c', after: null });
  });

  it('drop into an empty column returns null for both neighbors (end-of-column, per Move Wire Contract)', () => {
    expect(deriveNeighbors([], 0)).toEqual({ before: null, after: null });
  });

  it('a negative dropIndex clamps to 0 (front of column)', () => {
    expect(deriveNeighbors(['a', 'b'], -5)).toEqual({ before: null, after: 'a' });
  });

  it('a dropIndex beyond the column length clamps to the end of the column', () => {
    expect(deriveNeighbors(['a', 'b'], 99)).toEqual({ before: 'b', after: null });
  });

  // --- Interview-generated ---

  // from interview: Q7 (external dependencies controlled in tests) /
  // go-patterns purity discipline — a pure function must not mutate its
  // input; dnd-kit hands the caller arrays that React state elsewhere may
  // still hold a reference to.
  it('does not mutate the targetColumnIds array passed in', () => {
    const ids = ['a', 'b', 'c'];
    const snapshot = [...ids];
    deriveNeighbors(ids, 1);
    expect(ids).toEqual(snapshot);
  });

  // from interview: Q1 (conditions the acceptance criteria doesn't
  // explicitly describe) — purity: same inputs must always produce an
  // equal (not necessarily same-reference) result.
  it('is pure — the same inputs produce an equal result on repeated calls', () => {
    const first = deriveNeighbors(['a', 'b', 'c'], 2);
    const second = deriveNeighbors(['a', 'b', 'c'], 2);
    expect(first).toEqual(second);
  });

  // from interview: Q1 — the realistic same-column reorder case: the
  // dragged card's own id has already been removed from targetColumnIds
  // by the caller before this function ever runs (see contract note
  // above), so a drop landing on the far side of where the card used to
  // sit still resolves against the post-removal array, not the original.
  it('same-column reorder: dropping a removed card back in at a later index resolves against the post-removal order', () => {
    // Original column was ['a', 'b', 'c', 'd']; dragging 'a' out first
    // (caller's job) leaves ['b', 'c', 'd'] — dropping 'a' at index 2.
    expect(deriveNeighbors(['b', 'c', 'd'], 2)).toEqual({ before: 'c', after: 'd' });
  });
});
