// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 3 tests
// Interview-generated: 0 tests
// Total: 3 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Runs against the built binary (go:embed SPA + API) backed by a
// throwaway test Postgres — see playwright.config.ts and e2e/fixtures.ts.
// Covers the PRD/issue #6 acceptance criteria jsdom cannot exercise: a
// real pointer drag across columns updates Status, sets/clears
// FinishedAt per the locked invariant (DECISIONS.md "FinishedAt <-> Done
// invariant"), and the change survives a reload (persists through
// Repository.Move, not just local React state).

import { expect, test } from '@playwright/test';

import { closePool, insertBookmark, resetBookmarks, testUUID } from './fixtures';
import { dragCardTo } from './helpers';

test.describe('cross-column drag', () => {
  test.beforeEach(async () => {
    await resetBookmarks();
  });

  test.afterAll(async () => {
    await closePool();
  });

  test('dragging a card from Inbox to Reading updates its status and persists after reload', async ({ page }) => {
    const id = testUUID(1);
    await insertBookmark({ id, status: 'inbox', position: 'a', title: 'Move Me' });

    await page.goto('/');
    const card = page.getByTestId(`card-${id}`);
    await expect(card).toBeVisible();

    await dragCardTo(page, card, page.getByTestId('column-reading'));

    await expect(page.getByTestId('column-reading')).toContainText('Move Me');
    await expect(page.getByTestId('column-inbox')).not.toContainText('Move Me');

    await page.reload();
    await expect(page.getByTestId('column-reading')).toContainText('Move Me');
    await expect(page.getByTestId('column-inbox')).not.toContainText('Move Me');
  });

  test('dragging a card into Done sets its finished date, shown on the card, and persists after reload', async ({
    page,
  }) => {
    const id = testUUID(2);
    await insertBookmark({ id, status: 'inbox', position: 'a', title: 'Finish Me' });

    await page.goto('/');
    await dragCardTo(page, page.getByTestId(`card-${id}`), page.getByTestId('column-done'));

    await expect(page.getByTestId(`card-${id}`)).toContainText(/finished/i);

    await page.reload();
    await expect(page.getByTestId(`card-${id}`)).toContainText(/finished/i);
  });

  test('dragging a card out of Done clears its finished date, and persists after reload', async ({ page }) => {
    const id = testUUID(3);
    await insertBookmark({ id, status: 'done', position: 'a', title: 'Reopen Me', finishedAt: '2026-08-01T00:00:00Z' });

    await page.goto('/');
    await expect(page.getByTestId(`card-${id}`)).toContainText(/finished/i);

    await dragCardTo(page, page.getByTestId(`card-${id}`), page.getByTestId('column-inbox'));

    await expect(page.getByTestId(`card-${id}`)).not.toContainText(/finished/i);

    await page.reload();
    await expect(page.getByTestId(`card-${id}`)).not.toContainText(/finished/i);
  });
});
