// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 1 test
// Interview-generated: 1 test
// Total: 2 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Runs against the built binary + throwaway test Postgres — see
// playwright.config.ts and e2e/fixtures.ts. Locks the UI Contract's
// keyboard coordinate mapping (dnd-kit's default KeyboardSensor moves by
// pixel delta, not "next droppable" — cross-container keyboard movement
// needs a custom coordinateGetter, a Phase F implementation requirement
// this file locks the outcome of):
//   ArrowRight / ArrowLeft — move the lifted card to the next / previous
//     column, dropping at the end of that column's current order.
//   ArrowDown / ArrowUp   — move the lifted card later / earlier within
//     its current column's order.
//   Space                 — pick up (if not dragging) / drop (if dragging).
//   Escape                — cancel the drag; the card returns to its
//     original position.
// Announcements go through the aria-live region dnd-kit's DndContext
// renders (role="status") — see design.md Accessibility Baseline's
// example phrasing ("Picked up {title}. Moved to Reading, position 2 of
// 4. Dropped.") and App.test.tsx's wiring-presence check.

import { expect, test } from '@playwright/test';

import { closePool, insertBookmark, resetBookmarks, testUUID } from './fixtures';
import { getColumnOrder } from './helpers';

test.describe('keyboard drag', () => {
  test.beforeEach(async () => {
    await resetBookmarks();
  });

  test.afterAll(async () => {
    await closePool();
  });

  test('Space to pick up, ArrowRight to cross columns, Space to drop moves the card and announces each phase', async ({
    page,
  }) => {
    const id = testUUID(20);
    await insertBookmark({ id, status: 'inbox', position: 'a', title: 'Keyboard Card' });

    await page.goto('/');
    const card = page.getByTestId(`card-${id}`);
    await card.focus();
    await expect(card).toBeFocused();

    const liveRegion = page.getByRole('status');

    await page.keyboard.press('Space');
    await expect(liveRegion).toContainText(/picked up keyboard card/i);

    await page.keyboard.press('ArrowRight');
    await expect(liveRegion).toContainText(/moved to reading/i);

    await page.keyboard.press('Space');
    await expect(liveRegion).toContainText(/dropped/i);

    expect(await getColumnOrder(page, 'reading')).toEqual(['Keyboard Card']);
    expect(await getColumnOrder(page, 'inbox')).toEqual([]);

    await page.reload();
    expect(await getColumnOrder(page, 'reading')).toEqual(['Keyboard Card']);
  });

  // from interview: Q1 — full keyboard operability includes cancellation,
  // not just completion; a card picked up by mistake must be returnable
  // to its original position without a pointer.
  test('Escape cancels an in-progress keyboard drag and leaves the card in its original column', async ({
    page,
  }) => {
    const id = testUUID(21);
    await insertBookmark({ id, status: 'inbox', position: 'a', title: 'Cancel Me' });

    await page.goto('/');
    const card = page.getByTestId(`card-${id}`);
    await card.focus();

    const liveRegion = page.getByRole('status');

    await page.keyboard.press('Space');
    await expect(liveRegion).toContainText(/picked up cancel me/i);

    await page.keyboard.press('ArrowRight');
    await page.keyboard.press('Escape');
    await expect(liveRegion).toContainText(/cancelled/i);

    expect(await getColumnOrder(page, 'inbox')).toEqual(['Cancel Me']);
    expect(await getColumnOrder(page, 'reading')).toEqual([]);
  });
});
