// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 1 test
// Interview-generated: 1 test
// Total: 2 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Runs against the built binary + throwaway test Postgres — see
// playwright.config.ts and e2e/fixtures.ts. Covers PRD Goal 3 /
// AC "a card dragged to a new position within a column ... reloading the
// page shows the same order (Position round-trips through storage)."

import { expect, test } from '@playwright/test';

import { closePool, insertBookmark, resetBookmarks, testUUID } from './fixtures';
import { dragCardTo, getColumnOrder } from './helpers';

test.describe('within-column reorder', () => {
  test.beforeEach(async () => {
    await resetBookmarks();
  });

  test.afterAll(async () => {
    await closePool();
  });

  test('dragging a card to a new position within a column reorders it and persists after reload', async ({
    page,
  }) => {
    const a = testUUID(10);
    const b = testUUID(11);
    const c = testUUID(12);
    await insertBookmark({ id: a, status: 'inbox', position: 'b', title: 'Card A' });
    await insertBookmark({ id: b, status: 'inbox', position: 'c', title: 'Card B' });
    await insertBookmark({ id: c, status: 'inbox', position: 'd', title: 'Card C' });

    await page.goto('/');
    await expect(page.getByTestId(`card-${a}`)).toBeVisible();
    expect(await getColumnOrder(page, 'inbox')).toEqual(['Card A', 'Card B', 'Card C']);

    // Drag Card A past Card B — drop target is Card C's slot, so the
    // resulting order is B, A, C.
    await dragCardTo(page, page.getByTestId(`card-${a}`), page.getByTestId(`card-${c}`));

    await expect.poll(() => getColumnOrder(page, 'inbox')).toEqual(['Card B', 'Card A', 'Card C']);

    await page.reload();
    expect(await getColumnOrder(page, 'inbox')).toEqual(['Card B', 'Card A', 'Card C']);
  });

  // from interview: Q1 (conditions the AC doesn't explicitly describe) —
  // a reorder confined entirely within a column must not change any
  // other column's contents, and must not touch Status/FinishedAt (only
  // Position moves).
  test('reordering within Inbox does not move any card into Reading or Done', async ({ page }) => {
    const a = testUUID(13);
    const b = testUUID(14);
    await insertBookmark({ id: a, status: 'inbox', position: 'b', title: 'Stay A' });
    await insertBookmark({ id: b, status: 'inbox', position: 'c', title: 'Stay B' });

    await page.goto('/');
    await dragCardTo(page, page.getByTestId(`card-${b}`), page.getByTestId(`card-${a}`));

    await expect.poll(() => getColumnOrder(page, 'inbox')).toEqual(['Stay B', 'Stay A']);
    expect(await getColumnOrder(page, 'reading')).toEqual([]);
    expect(await getColumnOrder(page, 'done')).toEqual([]);
  });
});
