// Code generated by test-engine skill on 2026-07-09
// Issue: #2 — Postgres Adapter — Create & Board
// Blast radius tier: 1
// Auto-generated: 1 test
// Interview-generated: 1 test
// Total: 2 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
//go:build integration

package postgres_test

import (
	"context"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"

	"trailhead/internal/adapter/postgres"
)

// TestRunMigrations_FreshDB_CreatesSchema guards the wrong-embed-glob trap
// surfaced at interview Q11: if internal/adapter/postgres's go:embed
// pattern is wrong, m.Up() on an empty source also returns
// migrate.ErrNoChange, and RunMigrations reports success having created
// nothing. Asserting success is not enough — the table must exist.
// from interview: Q11
func TestRunMigrations_FreshDB_CreatesSchema(t *testing.T) {
	dsn := testDSN(t)
	require.NoError(t, postgres.RunMigrations(dsn), "RunMigrations should succeed against a fresh database")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	pool, err := pgxpool.New(ctx, dsn)
	require.NoError(t, err)
	defer pool.Close()

	var exists bool
	err = pool.QueryRow(ctx, "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bookmarks')").Scan(&exists)
	require.NoError(t, err)
	require.True(t, exists, "RunMigrations reported success but the bookmarks table does not exist — check the go:embed glob pattern")
}

// TestRunMigrations_SecondRun_NoChangeButSchemaIntact proves idempotency
// under a real repeated invocation (compose restart, CI, make migrate
// twice) — migrate.ErrNoChange must be swallowed and schema must remain.
// from interview: Q11
func TestRunMigrations_SecondRun_NoChangeButSchemaIntact(t *testing.T) {
	dsn := testDSN(t)
	require.NoError(t, postgres.RunMigrations(dsn), "first run should succeed")
	require.NoError(t, postgres.RunMigrations(dsn), "second run must swallow migrate.ErrNoChange, not surface it as a failure")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	pool, err := pgxpool.New(ctx, dsn)
	require.NoError(t, err)
	defer pool.Close()

	var exists bool
	err = pool.QueryRow(ctx, "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bookmarks')").Scan(&exists)
	require.NoError(t, err)
	require.True(t, exists, "schema must remain intact after a second RunMigrations call")
}
