// Code generated by test-engine skill on 2026-07-13
// Issue: #4 — [Phase 2] Postgres Adapter — Move (Tier 1)
// Blast radius tier: 1
// Interview-generated: 18 tests (no separate auto-generated scaffold —
// Move already exists as a real stub method on the real merged
// postgres.Repository, and interface-compliance-style coverage
// (closed-pool behavior) is already exercised generically by
// repository_test.go's TestRepository_AfterPoolClose_ReturnsError, so it
// is not duplicated per-method here).
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Driver note: same locked decision as repository_test.go — pgx/v5
// directly, not database/sql + lib/pq.
//
// Neighbor semantics (ports.go "MoveCommand", locked at Phase B):
// Before is the neighbor that should immediately PRECEDE the moved card
// (nil Before => front of column); After is the neighbor that should
// immediately FOLLOW it (nil After => back of column). When both are
// set, Before takes precedence and After is ignored outright — this is
// an unconditional precedence rule, not "fall back to After if Before
// turns out invalid" (see the adversarial test below).
//
// Cross-issue scope note: these tests require migration 000002
// (UNIQUE (status, position), see docs/issues/04-postgres-adapter-move.md
// "Decision B") and a revised Create that no longer assigns every new
// Inbox row the same fixed rank. Neither exists yet — this file is
// expected to fail at runtime (not compile time) until Dispatch
// implements Move, migration 000002, and the Create revision together.
// This is intended TDD red, not a defect in this file.
//
//go:build integration

package postgres_test

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"trailhead/internal/adapter"
	"trailhead/internal/adapter/postgres"
	"trailhead/internal/domain"
)

// --- Neighbor fallback (interview Q4) ---------------------------------

// from interview: Q4
func TestMove_MissingNeighborID_FallsBackToEndOfColumn(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	require.NoError(t, insertRawBookmarkAt(ctx, pool, testUUID(1), "hash-1", "reading", "b"))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, testUUID(2), "hash-2", "reading", "d"))

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/moving"})
	require.NoError(t, err)

	stale := domain.BookmarkID(testUUID(99)) // never inserted — deleted-between-drag-and-drop stand-in
	_, err = repo.Move(ctx, adapter.MoveCommand{
		ID:           moving.ID,
		TargetStatus: domain.StatusReading,
		Before:       &stale,
	})
	require.NoError(t, err, "a missing/stale neighbor ID must fall back to end-of-column, not fail the request")

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 3)
	assert.Equal(t, domain.BookmarkID(testUUID(1)), board.Reading[0].ID, "existing neighbors' relative order must be untouched")
	assert.Equal(t, domain.BookmarkID(testUUID(2)), board.Reading[1].ID)
	assert.Equal(t, moving.ID, board.Reading[2].ID, "moved bookmark must land last (end-of-column) in the target column")
}

// from interview: Q4
func TestMove_CrossStatusNeighborID_FallsBackToEndOfColumn(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	require.NoError(t, insertRawBookmarkAt(ctx, pool, testUUID(1), "hash-1", "reading", "b"))
	otherStatusID := domain.BookmarkID(testUUID(2))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(otherStatusID), "hash-2", "done", "b")) // wrong column for the Move below

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/moving"})
	require.NoError(t, err)

	_, err = repo.Move(ctx, adapter.MoveCommand{
		ID:           moving.ID,
		TargetStatus: domain.StatusReading,
		Before:       &otherStatusID, // exists, but in Done, not Reading
	})
	require.NoError(t, err, "a neighbor ID that exists but is not in TargetStatus must fall back to end-of-column")

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 2)
	assert.Equal(t, domain.BookmarkID(testUUID(1)), board.Reading[0].ID)
	assert.Equal(t, moving.ID, board.Reading[1].ID)
	require.Len(t, board.Done, 1, "the cross-status neighbor itself must be untouched, still in Done")
}

// from interview: Q4
func TestMove_SelfReferentialNeighborID_FallsBackToEndOfColumn(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	require.NoError(t, insertRawBookmarkAt(ctx, pool, testUUID(1), "hash-1", "reading", "b"))

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/moving"})
	require.NoError(t, err)

	self := moving.ID
	_, err = repo.Move(ctx, adapter.MoveCommand{
		ID:           moving.ID,
		TargetStatus: domain.StatusReading,
		After:        &self,
	})
	require.NoError(t, err, "a self-referential neighbor ID must fall back to end-of-column")

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 2)
	assert.Equal(t, domain.BookmarkID(testUUID(1)), board.Reading[0].ID)
	assert.Equal(t, moving.ID, board.Reading[1].ID)
}

// from interview: Q4
func TestMove_BeforeAndAfterBothSet_BeforeWins(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	cardA := domain.BookmarkID(testUUID(1))
	cardB := domain.BookmarkID(testUUID(2))
	cardC := domain.BookmarkID(testUUID(3))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(cardA), "hash-a", "reading", "b"))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(cardB), "hash-b", "reading", "d"))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(cardC), "hash-c", "reading", "f"))

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/moving"})
	require.NoError(t, err)

	// Before=cardB says "insert right after B, before C". After=cardA
	// disagrees ("insert right before A" — the front). Before must win.
	_, err = repo.Move(ctx, adapter.MoveCommand{
		ID:           moving.ID,
		TargetStatus: domain.StatusReading,
		Before:       &cardB,
		After:        &cardA,
	})
	require.NoError(t, err)

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 4)
	gotOrder := []domain.BookmarkID{board.Reading[0].ID, board.Reading[1].ID, board.Reading[2].ID, board.Reading[3].ID}
	assert.Equal(t, []domain.BookmarkID{cardA, cardB, moving.ID, cardC}, gotOrder,
		"Before must take precedence — the moved card lands between B and C, and the disagreeing After=A instruction is ignored outright")
}

// from interview: Q4 — adversarial: proves no reconciliation logic
// exists between Before and After.
func TestMove_BeforeInvalidAfterValid_FallsBackIgnoringValidAfter(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	validNeighbor := domain.BookmarkID(testUUID(1))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(validNeighbor), "hash-1", "reading", "b"))

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/moving"})
	require.NoError(t, err)

	stale := domain.BookmarkID(testUUID(99))
	_, err = repo.Move(ctx, adapter.MoveCommand{
		ID:           moving.ID,
		TargetStatus: domain.StatusReading,
		Before:       &stale,         // invalid
		After:        &validNeighbor, // valid, but must still be ignored — Before is set at all, so After is never consulted
	})
	require.NoError(t, err)

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 2)
	assert.Equal(t, validNeighbor, board.Reading[0].ID)
	assert.Equal(t, moving.ID, board.Reading[1].ID,
		"an invalid Before must fall all the way to end-of-column — it must NOT fall back to honoring the perfectly-valid After instead")
}

// --- FinishedAt <-> Done invariant (interview Q5) ---------------------

// from interview: Q5
func TestMove_IntoDone_SetsFinishedAtToClockAndUpdatedAt(t *testing.T) {
	repo, _, frozen := newTestRepository(t)
	ctx := context.Background()

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)
	require.Nil(t, moving.FinishedAt)

	got, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusDone})
	require.NoError(t, err)

	require.NotNil(t, got.FinishedAt)
	assert.True(t, got.FinishedAt.Equal(frozen), "FinishedAt must equal the injected clock's instant, not a fuzzy 'around now' range")
	assert.True(t, got.UpdatedAt.Equal(frozen), "UpdatedAt must bump on every successful Move")
	assert.Equal(t, domain.StatusDone, got.Status)
}

// from interview: Q5, Q11 (SQL NULL guard)
func TestMove_OutOfDone_ClearsFinishedAtToNULL(t *testing.T) {
	repo, pool, frozen := newTestRepository(t)
	ctx := context.Background()

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	inDone, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusDone})
	require.NoError(t, err)
	require.NotNil(t, inDone.FinishedAt)

	got, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusReading})
	require.NoError(t, err)
	assert.Nil(t, got.FinishedAt, "leaving Done must clear FinishedAt")
	assert.True(t, got.UpdatedAt.Equal(frozen))

	var raw *time.Time
	require.NoError(t, pool.QueryRow(ctx, "SELECT finished_at FROM bookmarks WHERE id = $1", string(moving.ID)).Scan(&raw))
	assert.Nil(t, raw, "the stored column must be a real SQL NULL, not a Go zero-time value that happens to scan back as non-nil")
}

// from interview: Q5 — the adversarial case: an advanceable clock is
// required to distinguish "preserved" from "re-stamped to the same
// instant," which a single fixed clock cannot express.
func TestMove_DoneToDone_PreservesFinishedAtButBumpsUpdatedAt(t *testing.T) {
	pool := newTestPool(t)
	ctx := context.Background()

	t1 := time.Date(2026, 7, 13, 9, 0, 0, 0, time.UTC)
	clock := newMutableClock(t1)
	repo := postgres.New(pool, clock.Now)

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	enteredDone, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusDone})
	require.NoError(t, err)
	require.NotNil(t, enteredDone.FinishedAt)
	assert.True(t, enteredDone.FinishedAt.Equal(t1))

	t2 := t1.Add(3 * time.Hour)
	clock.Advance(3 * time.Hour)

	// Same-column reorder within Done — TargetStatus is Done again, and
	// the bookmark's current Status is already Done.
	reordered, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusDone})
	require.NoError(t, err)
	require.NotNil(t, reordered.FinishedAt)
	assert.True(t, reordered.FinishedAt.Equal(t1), "a Done->Done reorder must PRESERVE the original FinishedAt, not re-stamp it to the new clock instant")
	assert.True(t, reordered.UpdatedAt.Equal(t2), "UpdatedAt must still bump to the new clock instant even though FinishedAt is preserved")
}

// from interview: Q5
func TestMove_NonDoneToNonDone_FinishedAtStaysNil(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	got, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusReading})
	require.NoError(t, err)
	assert.Nil(t, got.FinishedAt, "a non-Done -> non-Done move must leave FinishedAt nil")
	assert.Equal(t, domain.StatusReading, got.Status)
}

// --- NotFound (interview Q6) -------------------------------------------

// from interview: Q6 — given valid neighbors, to prove the ID check
// gates the operation before any fallback/rank logic runs.
func TestMove_UnknownID_ReturnsNotFound_NoSideEffect(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	neighborID := domain.BookmarkID(testUUID(1))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(neighborID), "hash-1", "reading", "b"))

	unknown := domain.BookmarkID(testUUID(404))
	_, err := repo.Move(ctx, adapter.MoveCommand{
		ID:           unknown,
		TargetStatus: domain.StatusReading,
		After:        &neighborID,
	})
	require.Error(t, err)

	var repoErr *adapter.RepositoryError
	require.True(t, errors.As(err, &repoErr), "error must be a *adapter.RepositoryError")
	assert.Equal(t, adapter.ErrKindNotFound, repoErr.Kind)

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 1, "the unknown Move must not insert, delete, or otherwise touch any row")
	assert.Equal(t, neighborID, board.Reading[0].ID)
}

// --- Position / rank ordering (interview Q2, Q3) -----------------------

// from interview: Q2, Q3 — the degenerate empty-column starting rank,
// tested separately from the general between-neighbors case.
func TestMove_IntoEmptyColumn_ValidStartingRank(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/moving"})
	require.NoError(t, err)

	got, err := repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusDone})
	require.NoError(t, err, "moving into a column with no existing rows (both Before and After nil) must succeed with a valid starting rank")
	assert.Equal(t, domain.StatusDone, got.Status)
	assert.NotEmpty(t, got.Position)

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Done, 1)
	assert.Equal(t, moving.ID, board.Done[0].ID)
}

// from interview: Q2, Q3 — black-box stress test for the fractional-rank
// algorithm's length-extension behavior: repeatedly inserting into the
// same narrowing gap must never produce a duplicate or out-of-order
// Position. Tests assert the ordering invariant only, never a literal
// rank string (Q2).
func TestMove_RepeatedInsertsIntoSameGap_MaintainsStrictOrder(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	lowID := domain.BookmarkID(testUUID(1))
	highID := domain.BookmarkID(testUUID(2))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(lowID), "hash-low", "reading", "b"))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(highID), "hash-high", "reading", "z"))

	const n = 12
	predecessor := lowID
	for i := 0; i < n; i++ {
		card, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: fmt.Sprintf("https://example.com/gap-%d", i)})
		require.NoError(t, err)

		pred, succ := predecessor, highID
		_, err = repo.Move(ctx, adapter.MoveCommand{
			ID:           card.ID,
			TargetStatus: domain.StatusReading,
			Before:       &pred,
			After:        &succ,
		})
		require.NoError(t, err, "insert %d into the narrowing gap must succeed without exhausting rank precision", i)
		predecessor = card.ID
	}

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, n+2)

	for i := 1; i < len(board.Reading); i++ {
		assert.Less(t, string(board.Reading[i-1].Position), string(board.Reading[i].Position),
			"Position must be strictly increasing across every row in the column — a repeated narrow-gap insert must never produce a duplicate or out-of-order rank")
	}
	assert.Equal(t, lowID, board.Reading[0].ID)
	assert.Equal(t, highID, board.Reading[len(board.Reading)-1].ID)
}

// --- Position collision / Decision B (interview Q3, Q7, Q12) -----------

// from interview: Q7 — the livelock guard: the loser must re-resolve
// neighbor adjacency and retry, not reuse stale ranks and recompute the
// same colliding midpoint forever.
func TestMove_ConcurrentSameGapMoves_BothSucceedDistinctRanksCorrectOrder(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	lowID := domain.BookmarkID(testUUID(1))
	highID := domain.BookmarkID(testUUID(2))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(lowID), "hash-low", "reading", "b"))
	require.NoError(t, insertRawBookmarkAt(ctx, pool, string(highID), "hash-high", "reading", "z"))

	cardA, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/card-a"})
	require.NoError(t, err)
	cardB, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/card-b"})
	require.NoError(t, err)

	var wg sync.WaitGroup
	errs := make([]error, 2)
	low, high := lowID, highID
	wg.Add(2)
	go func() {
		defer wg.Done()
		_, errs[0] = repo.Move(ctx, adapter.MoveCommand{ID: cardA.ID, TargetStatus: domain.StatusReading, Before: &low, After: &high})
	}()
	go func() {
		defer wg.Done()
		_, errs[1] = repo.Move(ctx, adapter.MoveCommand{ID: cardB.ID, TargetStatus: domain.StatusReading, Before: &low, After: &high})
	}()
	wg.Wait()

	require.NoError(t, errs[0], "both movers into the same gap must eventually succeed — the loser must re-resolve neighbor adjacency and retry, not fail the request")
	require.NoError(t, errs[1])

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Reading, 4)

	positions := make(map[domain.BookmarkID]int, 4)
	for i, b := range board.Reading {
		positions[b.ID] = i
	}
	assert.Equal(t, 0, positions[lowID], "low must remain first")
	assert.Equal(t, 3, positions[highID], "high must remain last")
	assert.NotEqual(t, positions[cardA.ID], positions[cardB.ID], "the two concurrently-moved cards must land at distinct positions, not a collided/duplicate rank")
	for i := 1; i < len(board.Reading); i++ {
		assert.Less(t, string(board.Reading[i-1].Position), string(board.Reading[i].Position), "final order must be a strict byte-order chain — no duplicate or out-of-order Position")
	}
}

// from interview: Q12 — proves migration 000002's index exists and
// fires; not a defensive-migration-code test (none was asked for).
func TestSchema_StatusPositionUniqueIndex_FiresOnDuplicateRawInsert(t *testing.T) {
	_, pool, _ := newTestRepository(t)
	ctx := context.Background()

	require.NoError(t, insertRawBookmarkAt(ctx, pool, testUUID(1), "hash-1", "inbox", "m"))
	err := insertRawBookmarkAt(ctx, pool, testUUID(2), "hash-2", "inbox", "m")
	require.Error(t, err, "a second row with the same (status, position) pair must violate the unique index added by migration 000002")

	var pgErr *pgconn.PgError
	require.True(t, errors.As(err, &pgErr), "error must be a *pgconn.PgError")
	assert.Equal(t, "23505", pgErr.Code)
	assert.Equal(t, "bookmarks_status_position_unique_idx", pgErr.ConstraintName,
		`must be the locked index name — see docs/issues/04-postgres-adapter-move.md "Locked index name for migration 000002"`)
}

// from interview: Q11 — proves migration 000002 did not drop and
// recreate the position column without its collation, re-proving
// repository_test.go's TestBoard_PositionOrderingByteOrder_RegardlessOfServerLocale
// guarantee post-migration.
func TestSchema_StatusPositionColumn_CollationStillC(t *testing.T) {
	_, pool, _ := newTestRepository(t)
	ctx := context.Background()

	var collation *string
	err := pool.QueryRow(ctx,
		`SELECT collation_name FROM information_schema.columns WHERE table_name = 'bookmarks' AND column_name = 'position'`,
	).Scan(&collation)
	require.NoError(t, err)
	require.NotNil(t, collation, `position column must still have an explicit collation after migration 000002 replaces its index`)
	assert.Equal(t, "C", *collation, `migration 000002 must not have dropped and recreated the position column without COLLATE "C"`)
}

// --- Board snapshot consistency (interview Q8) --------------------------

// from interview: Q8 — a deterministic controlled-transaction test, not
// a goroutine race: a raw in-flight UPDATE stands in for a paused Move
// since this tests Board's read-snapshot consistency, which is
// writer-agnostic.
func TestBoard_DuringInFlightMoveTransaction_SnapshotConsistent(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	tx, err := pool.Begin(ctx)
	require.NoError(t, err)

	_, err = tx.Exec(ctx, "UPDATE bookmarks SET status = 'reading' WHERE id = $1", string(moving.ID))
	require.NoError(t, err)

	boardDuring, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err, "Board must not block on or error against an in-flight uncommitted writer")
	require.Len(t, boardDuring.Inbox, 1, "Board must see the pre-transaction committed state — the uncommitted UPDATE must be invisible")
	assert.Empty(t, boardDuring.Reading)
	assert.Equal(t, moving.ID, boardDuring.Inbox[0].ID)

	require.NoError(t, tx.Commit(ctx))

	boardAfter, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, boardAfter.Reading, 1, "after commit, Board must see the new column")
	assert.Empty(t, boardAfter.Inbox)
	assert.Equal(t, moving.ID, boardAfter.Reading[0].ID)
}

// --- Partial-failure / commit-boundary contract (interview Q9, Q10) ----

// from interview: Q10 — pre-commit failure must leave the row completely
// unchanged (mirrors Create's contract from issue #2).
func TestMove_ContextCanceledBeforeCommit_RowUnchanged(t *testing.T) {
	repo, pool, _ := newTestRepository(t)

	moving, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	canceled, cancel := context.WithCancel(context.Background())
	cancel()

	_, err = repo.Move(canceled, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.StatusDone})
	require.Error(t, err, "Move called with an already-canceled context must fail before any write lands")

	var (
		status     string
		position   string
		finishedAt *time.Time
	)
	require.NoError(t, pool.QueryRow(context.Background(), "SELECT status, position, finished_at FROM bookmarks WHERE id = $1", string(moving.ID)).
		Scan(&status, &position, &finishedAt))
	assert.Equal(t, string(domain.StatusInbox), status, "a pre-commit failure must leave status completely unchanged")
	assert.Equal(t, string(moving.Position), position, "a pre-commit failure must leave position completely unchanged")
	assert.Nil(t, finishedAt, "a pre-commit failure must not have set finished_at")
}

// --- E1 defense-in-depth (interview Q1) ---------------------------------

// from interview: Q1 — the one defensive test this issue owns for E1;
// the 400-rejection behavior itself belongs to issue #5.
func TestMove_InvalidTargetStatus_FailsCleanlyViaCheckConstraint(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	moving, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	_, err = repo.Move(ctx, adapter.MoveCommand{ID: moving.ID, TargetStatus: domain.Status("bogus")})
	require.Error(t, err, `a garbage TargetStatus that somehow reaches Move must fail cleanly, not corrupt the row — internal/api (issue #5) is responsible for rejecting this before Move is ever called (DECISIONS.md "MoveCommand.TargetStatus — Validation Ownership (E1, resolved)")`)

	var repoErr *adapter.RepositoryError
	assert.False(t, errors.As(err, &repoErr), "a CHECK-constraint failure must surface as a plain infrastructure error, not a classified *adapter.RepositoryError")

	var status string
	require.NoError(t, pool.QueryRow(ctx, "SELECT status FROM bookmarks WHERE id = $1", string(moving.ID)).Scan(&status))
	assert.Equal(t, string(domain.StatusInbox), status, "the row must be completely unchanged after a rejected garbage status")
}
