// Code generated by test-engine skill on 2026-07-09
// Issue: #2 — Postgres Adapter — Create & Board
// Blast radius tier: 1
// Auto-generated: 5 tests
// Interview-generated: 21 tests
// Total: 26 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Driver note: locked decision (ARCHITECTURE_RFC.md "Postgres Driver") is
// github.com/jackc/pgx/v5 used directly, NOT database/sql + lib/pq. The
// shared databases/postgres DBA skill (status: draft) is written for the
// lib/pq stack and a different project's domain — logged as process gap
// H-07, not patched mid-session.
//
// Review-pass fixes applied (2026-07-09, before first commit): removed
// two nil-context tests (pgx panics on a literal nil context before the
// adapter can return an error, and no explicit nil-guard requirement was
// ever locked — dropped rather than inventing one); removed the fragile
// Location().String()=="UTC" assertion in the timezone test (couples to
// pgx's scan-back location; the frozen-clock equality already covers the
// real risk); added missing "fmt" import.
//
//go:build integration

package postgres_test

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"trailhead/internal/adapter"
	"trailhead/internal/adapter/postgres"
	"trailhead/internal/domain"
)

// --- Interface compliance (2a) ---------------------------------------

// auto: interface compliance
func TestRepository_AfterPoolClose_ReturnsError(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	pool.Close()
	_, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/a"})
	assert.Error(t, err, "Create after pool Close() must return an error, not panic")
}

// --- Happy path (from Acceptance Criteria) ---------------------------
//
// NOTE: BoardFilter.Tags is intentionally not exercised anywhere in this
// file. Tag filtering beyond an empty filter is out of scope for issue #2
// — see the issue body's "Out of Scope" section ("Tag filtering in Board
// beyond an empty filter (Phase D)") — deferred, not an accidental gap.
// Every Board call below uses adapter.BoardFilter{}.

// auto: acceptance criteria
func TestCreateBookmark_PersistsAndDefaults(t *testing.T) {
	repo, _, frozen := newTestRepository(t)
	ctx := context.Background()

	got, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/blog/my-great-post"})
	require.NoError(t, err)

	assert.Equal(t, domain.CanonicalURL("https://example.com/blog/my-great-post"), got.CanonicalURL)
	assert.Equal(t, domain.DeriveIdentityHash(got.CanonicalURL), got.IdentityHash)
	// "example.com - My Great Post" — DECISIONS.md "Title Defaulting":
	// hostname + de-slugified last path segment, plain hyphen separator
	// (not em dash), title-cased.
	assert.Equal(t, "example.com - My Great Post", got.Title)
	assert.Equal(t, domain.StatusInbox, got.Status)
	assert.True(t, got.CreatedAt.Equal(frozen), "CreatedAt should equal the injected clock's instant")
	assert.True(t, got.UpdatedAt.Equal(frozen), "UpdatedAt should equal the injected clock's instant")
	assert.NotEmpty(t, got.ID)
}

// auto: acceptance criteria
func TestCreateBookmark_DuplicateReturnsExisting(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	first, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.Error(t, err)

	var repoErr *adapter.RepositoryError
	require.True(t, errors.As(err, &repoErr), "error must be a *adapter.RepositoryError")
	assert.Equal(t, adapter.ErrKindDuplicate, repoErr.Kind)
	require.NotNil(t, repoErr.Existing)
	assert.Equal(t, first.ID, repoErr.Existing.ID)
}

// auto: acceptance criteria
func TestCreateBookmark_InvalidURLRejected(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "not a url"})
	require.Error(t, err)

	var repoErr *adapter.RepositoryError
	require.True(t, errors.As(err, &repoErr))
	assert.Equal(t, adapter.ErrKindInvalidURL, repoErr.Kind)

	var count int
	require.NoError(t, pool.QueryRow(ctx, "SELECT count(*) FROM bookmarks").Scan(&count))
	assert.Zero(t, count, "no row should be inserted for an invalid URL")
}

// auto: acceptance criteria
func TestBoard_GroupsByStatusOrdered(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/1"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/2"})
	require.NoError(t, err)

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)

	assert.Len(t, board.Inbox, 2)
	assert.Empty(t, board.Reading)
	assert.Empty(t, board.Done)
}

// --- Golden invariant: cosmetic-variant dedup (interview Q1, Q10) -----

// from interview: Q1, Q10
func TestCreateBookmark_CosmeticVariants_AllDedupToSameExisting(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	original, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/x"})
	require.NoError(t, err)

	variants := []struct {
		name string
		url  string
	}{
		{"http scheme", "http://example.com/x"},
		{"www prefix", "https://www.example.com/x"},
		{"trailing slash", "https://example.com/x/"},
		{"utm_source tracking param", "https://example.com/x?utm_source=foo"},
		{"gclid tracking param", "https://example.com/x?gclid=abc123"},
		{"fbclid tracking param", "https://example.com/x?fbclid=xyz"},
	}

	for _, v := range variants {
		t.Run(v.name, func(t *testing.T) {
			_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: v.url})
			require.Error(t, err)
			var repoErr *adapter.RepositoryError
			require.True(t, errors.As(err, &repoErr))
			assert.Equal(t, adapter.ErrKindDuplicate, repoErr.Kind)
			require.NotNil(t, repoErr.Existing)
			assert.Equal(t, original.ID, repoErr.Existing.ID, "variant %q must dedup to the original bookmark", v.url)
		})
	}

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	assert.Len(t, board.Inbox, 1, "exactly one entry should exist for this link after all variant attempts")
}

// --- Surprising-but-correct cases (interview Q4) ----------------------

func TestCreateBookmark_QueryParamAsymmetry_TrackingStrippedMeaningfulKept(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	// Tracking params are stripped by the locked deny-list rule.
	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a?utm_source=x"})
	require.Error(t, err, "utm_source is a tracking param and must be stripped, deduping with the bare URL")

	// Meaningful params are preserved — genuinely distinct bookmarks.
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/b?page=2"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/b?page=3"})
	require.NoError(t, err, "page=2 and page=3 are meaningfully different bookmarks, not a duplicate")
}

func TestCreateBookmark_FragmentCollapse_SameBookmark(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a#intro"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a#conclusion"})
	require.Error(t, err, "fragments are dropped during canonicalization — different anchors on the same page are the same bookmark")
}

func TestCreateBookmark_HTTPAndHTTPS_SameHostCollapse(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "http://example.com/x"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/x"})
	require.Error(t, err, "http and https of the same host must collapse to one bookmark per the locked scheme-forcing rule")
}

func TestCreateBookmark_DefaultTitle_URLDerivedNotFetched(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	got, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/blog/my-great-post"})
	require.NoError(t, err)
	assert.Equal(t, "example.com - My Great Post", got.Title)
}

func TestCreateBookmark_TagsLowercasedAndDeduped(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	got, err := repo.Create(context.Background(), domain.NewBookmark{
		OriginalURL: "https://example.com/a",
		Tags:        domain.Tags{"Go", "go", "GO"},
	})
	require.NoError(t, err)
	assert.Equal(t, domain.Tags{"go"}, got.Tags)
}

// --- Optional-field nil path (interview Q6 — Islamic Chatbot scar) ----

// from interview: Q6
func TestCreateBookmark_NilAuthorAndFinishedAt_StoredAsSQLNull(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	got, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	assert.Nil(t, got.Author, "Author must be nil, not an empty string, when not set")
	assert.Nil(t, got.FinishedAt)

	var authorIsNull, finishedAtIsNull bool
	err = pool.QueryRow(ctx,
		"SELECT author IS NULL, finished_at IS NULL FROM bookmarks WHERE id = $1", got.ID,
	).Scan(&authorIsNull, &finishedAtIsNull)
	require.NoError(t, err)
	assert.True(t, authorIsNull, "author column must be SQL NULL, not an empty string")
	assert.True(t, finishedAtIsNull, "finished_at column must be SQL NULL on an Inbox bookmark")
}

// from interview: Q1
func TestCreateBookmark_LeavesFinishedAtNil_InboxInvariant(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	got, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)
	assert.Equal(t, domain.StatusInbox, got.Status)
	assert.Nil(t, got.FinishedAt)
}

// --- Determinism and timestamp exactness -------------------------------

// from interview: Q3
func TestCreateBookmark_IdentityHashDeterministic_MatchesDedupLookup(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	got, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)

	canon, err := domain.Canonicalize("https://example.com/a")
	require.NoError(t, err)
	assert.Equal(t, domain.DeriveIdentityHash(canon), got.IdentityHash)
}

// from interview: Q7
func TestCreateBookmark_CreatedAtEqualsUpdatedAt_FrozenClock(t *testing.T) {
	repo, _, frozen := newTestRepository(t)
	got, err := repo.Create(context.Background(), domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)
	assert.True(t, got.CreatedAt.Equal(got.UpdatedAt), "CreatedAt and UpdatedAt must be exactly equal on Create")
	assert.True(t, got.CreatedAt.Equal(frozen), "both must equal the single injected clock value, not two independent now() calls")
}

// from interview: Q5
func TestCreateBookmark_TimestampsUTC_RegardlessOfServerTimezone(t *testing.T) {
	repo, pool, frozen := newTestRepository(t)
	ctx := context.Background()

	_, err := pool.Exec(ctx, "SET TIME ZONE 'America/New_York'")
	require.NoError(t, err)
	t.Cleanup(func() {
		_, _ = pool.Exec(context.Background(), "SET TIME ZONE 'UTC'")
	})

	got, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)
	assert.True(t, got.CreatedAt.Equal(frozen), "the stored instant must match the frozen UTC clock exactly, independent of session display timezone")
}

// --- Position ordering under non-C locale (interview Q3, Q5) ---------

// from interview: Q3, Q5
func TestBoard_PositionOrderingByteOrder_RegardlessOfServerLocale(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx := context.Background()

	var collation *string
	err := pool.QueryRow(ctx,
		`SELECT collation_name FROM information_schema.columns WHERE table_name = 'bookmarks' AND column_name = 'position'`,
	).Scan(&collation)
	require.NoError(t, err)
	require.NotNil(t, collation, "position column must have an explicit collation")
	assert.Equal(t, "C", *collation, `position column must be COLLATE "C" for byte-order guarantees`)

	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/1"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/2"})
	require.NoError(t, err)

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board.Inbox, 2)
	assert.LessOrEqual(t, string(board.Inbox[0].Position), string(board.Inbox[1].Position), "Board must return byte-order position ordering")
}

// --- Board partition and empty-state contract (interview Q1, Q10) ----

func TestBoard_EmptyTable_ReturnsThreeEmptyNonNilSlices(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	board, err := repo.Board(context.Background(), adapter.BoardFilter{})
	require.NoError(t, err)
	assert.NotNil(t, board.Inbox, "Inbox must be an empty slice, not nil — see ARCHITECTURE_RFC.md Serialization Spec")
	assert.NotNil(t, board.Reading)
	assert.NotNil(t, board.Done)
	assert.Empty(t, board.Inbox)
	assert.Empty(t, board.Reading)
	assert.Empty(t, board.Done)
}

func TestBoard_PartitionIsTotalAndDisjoint(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	const n = 5
	for i := 0; i < n; i++ {
		_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: fmt.Sprintf("https://example.com/%d", i)})
		require.NoError(t, err)
	}

	board, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	total := len(board.Inbox) + len(board.Reading) + len(board.Done)
	assert.Equal(t, n, total, "every stored bookmark must appear in exactly one column")
}

// --- Concurrency (interview Q8) ---------------------------------------

// from interview: Q8
func TestCreateBookmark_ConcurrentDifferentURLs_StableOrderByPositionThenID(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	const n = 10
	var wg sync.WaitGroup
	errs := make([]error, n)
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: fmt.Sprintf("https://example.com/concurrent-%d", i)})
			errs[i] = err
		}(i)
	}
	wg.Wait()

	for i, err := range errs {
		assert.NoError(t, err, "concurrent Create %d should succeed — different URLs, no dedup conflict", i)
	}

	board1, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	board2, err := repo.Board(ctx, adapter.BoardFilter{})
	require.NoError(t, err)
	require.Len(t, board1.Inbox, n)
	require.Len(t, board2.Inbox, n)
	for i := range board1.Inbox {
		assert.Equal(t, board1.Inbox[i].ID, board2.Inbox[i].ID, "Board order must be stable across repeated calls given position ties")
	}
}

// --- Partial failure / commit boundary (interview Q9) ------------------

// from interview: Q9
func TestCreateBookmark_RollbackOnFailureBeforeCommit_NoRowExists(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.Error(t, err, "Create with an already-canceled context must fail")

	var count int
	require.NoError(t, pool.QueryRow(context.Background(), "SELECT count(*) FROM bookmarks").Scan(&count))
	assert.Zero(t, count, "no row should exist when the context was canceled before commit")
}

// from interview: Q9
func TestCreateBookmark_RowVisibleAfterCommit_RetryIsIdempotent(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	first, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err, "the initial Create commits successfully")

	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.Error(t, err)
	var repoErr *adapter.RepositoryError
	require.True(t, errors.As(err, &repoErr))
	assert.Equal(t, adapter.ErrKindDuplicate, repoErr.Kind, "retrying the same URL after a successful commit must be idempotent, not create a second row")
	assert.Equal(t, first.ID, repoErr.Existing.ID)
}

// --- Infrastructure failure paths (interview Q2) -----------------------

// from interview: Q2
func TestCreateBookmark_ContextCanceledMidQuery_WrappedInfraError_NoPartialWrite(t *testing.T) {
	repo, pool, _ := newTestRepository(t)
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Millisecond)
	defer cancel()
	time.Sleep(5 * time.Millisecond)

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.Error(t, err)

	var repoErr *adapter.RepositoryError
	assert.False(t, errors.As(err, &repoErr), "a context deadline must surface as a plain wrapped infra error, never a *RepositoryError with a domain Kind")

	var count int
	require.NoError(t, pool.QueryRow(context.Background(), "SELECT count(*) FROM bookmarks").Scan(&count))
	assert.Zero(t, count, "no partial row should be written when the context deadline is exceeded")
}

// from interview: Q2
func TestCreateBookmark_PoolAcquireTimeout_WrappedInfraError(t *testing.T) {
	dsn := testDSN(t)
	ctx := context.Background()

	cfg, err := pgxpool.ParseConfig(dsn)
	require.NoError(t, err)
	cfg.MaxConns = 1
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	require.NoError(t, err)
	defer pool.Close()

	held, err := pool.Acquire(ctx)
	require.NoError(t, err)
	defer held.Release()

	repo := postgres.New(pool, fixedClock(time.Now().UTC()))
	acquireCtx, cancel := context.WithTimeout(ctx, 200*time.Millisecond)
	defer cancel()

	_, err = repo.Create(acquireCtx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.Error(t, err, "Create must fail when the pool cannot acquire a connection before the context deadline")

	var repoErr *adapter.RepositoryError
	assert.False(t, errors.As(err, &repoErr), "pool acquire timeout is an infrastructure failure, never a domain ErrorKind")
}

// --- Constraint-name-specific error mapping (interview Q2, Q6) --------

// from interview: Q2, Q6
func TestIsDuplicateConstraintViolation_IdentityHashConstraint_True(t *testing.T) {
	repo, _, _ := newTestRepository(t)
	ctx := context.Background()

	_, err := repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.NoError(t, err)
	_, err = repo.Create(ctx, domain.NewBookmark{OriginalURL: "https://example.com/a"})
	require.Error(t, err)

	var repoErr *adapter.RepositoryError
	require.True(t, errors.As(err, &repoErr))
	assert.Equal(t, adapter.ErrKindDuplicate, repoErr.Kind)
}

// TestIsDuplicateConstraintViolation_OtherConstraint_False: gen_random_uuid()
// makes a real bookmarks_pkey collision un-inducible through the public
// Create API, so this forces one via a raw duplicate-id insert.
// from interview: Q2, Q6
func TestIsDuplicateConstraintViolation_OtherConstraint_False(t *testing.T) {
	_, pool, _ := newTestRepository(t)
	ctx := context.Background()

	const sharedID = "11111111-1111-1111-1111-111111111111"
	require.NoError(t, insertRawBookmark(ctx, pool, sharedID, "hash-one"))

	err := insertRawBookmark(ctx, pool, sharedID, "hash-two")
	require.Error(t, err, "inserting a second row with the same id must violate bookmarks_pkey")

	assert.False(t, postgres.IsDuplicateConstraintViolation(err), "a bookmarks_pkey violation must NOT be classified as a duplicate-URL (bookmarks_identity_hash_idx) violation")
}
