// Code generated by test-engine skill on 2026-07-09
// Issue: #2 — Postgres Adapter — Create & Board
// Blast radius tier: 1
// Shared test setup — not itself a test file, but build-tagged the same
// way so it only compiles under `-tags integration`.
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
//go:build integration

package postgres_test

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"trailhead/internal/adapter/postgres"
)

// testDSN returns TEST_DATABASE_URL or fails loudly — a missing env var
// is a loud t.Fatal, never a silent t.Skip.
func testDSN(t *testing.T) string {
	t.Helper()
	dsn := os.Getenv("TEST_DATABASE_URL")
	if dsn == "" {
		t.Fatal("TEST_DATABASE_URL is not set — integration tests require an explicit test database, not a silent skip")
	}
	return dsn
}

// newTestPool runs migrations against a fresh connection to prove the real
// go:embed source (see migrate_test.go rationale), then returns a pooled
// connection for the tests themselves. t.Cleanup truncates and closes.
func newTestPool(t *testing.T) *pgxpool.Pool {
	t.Helper()
	dsn := testDSN(t)

	if err := postgres.RunMigrations(dsn); err != nil {
		t.Fatalf("RunMigrations: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("pgxpool.New: %v", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		t.Fatalf("pool.Ping: %v", err)
	}

	t.Cleanup(func() {
		truncateBookmarks(t, pool)
		pool.Close()
	})

	truncateBookmarks(t, pool)
	return pool
}

// truncateBookmarks resets table state between tests.
func truncateBookmarks(t *testing.T, pool *pgxpool.Pool) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if _, err := pool.Exec(ctx, "TRUNCATE TABLE bookmarks"); err != nil {
		t.Fatalf("truncateBookmarks: %v", err)
	}
}

// newTestRepository wires a Repository over a fresh pool with a frozen
// clock — see DECISIONS.md "Timestamp source — injectable clock."
func newTestRepository(t *testing.T) (*postgres.Repository, *pgxpool.Pool, time.Time) {
	t.Helper()
	pool := newTestPool(t)
	frozen := time.Date(2026, 7, 9, 12, 0, 0, 0, time.UTC)
	repo := postgres.New(pool, fixedClock(frozen))
	return repo, pool, frozen
}

// fixedClock returns a clock function that always reports t — see
// DECISIONS.md "Timestamp source — injectable clock."
func fixedClock(t time.Time) func() time.Time {
	return func() time.Time { return t }
}

// insertRawBookmark bypasses Repository.Create entirely — used only by
// tests that need to induce a specific raw-SQL condition (e.g. a
// non-identity-hash constraint violation) that Create's own write path
// cannot produce under normal operation, since gen_random_uuid() makes a
// real bookmarks_pkey collision vanishingly improbable through the public
// API. tags is omitted deliberately — ARCHITECTURE_RFC.md "Persistence
// Schema" declares `tags jsonb NOT NULL DEFAULT '[]'::jsonb`, so the
// omission defaults cleanly.
func insertRawBookmark(ctx context.Context, pool *pgxpool.Pool, id, identityHash string) error {
	const q = `
		INSERT INTO bookmarks
			(id, original_url, canonical_url, identity_hash, title, status, position, created_at, updated_at)
		VALUES
			($1, $2, $3, $4, 'raw test row', 'inbox', 'a', now(), now())
	`
	_, err := pool.Exec(ctx, q, id, fmt.Sprintf("https://example.com/%s", identityHash), fmt.Sprintf("https://example.com/%s", identityHash), identityHash)
	return err
}
