// Code generated by test-engine skill on 2026-07-09
// Issue: #2 — Postgres Adapter — Create & Board
// Blast radius tier: 1
// Shared test setup — not itself a test file, but build-tagged the same
// way so it only compiles under `-tags integration`.
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Addendum (2026-07-13, issue #4 Pre-Phase F — re-running test-engine
// per this file's own header, pending developer re-approval): added
// mutableClock, insertRawBookmarkAt, and testUUID for move_test.go.
// Every existing line above this addendum is unchanged.
//
//go:build integration

package postgres_test

import (
	"context"
	"fmt"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"trailhead/internal/adapter/postgres"
)

// testDSN returns TEST_DATABASE_URL or fails loudly — a missing env var
// is a loud t.Fatal, never a silent t.Skip.
func testDSN(t *testing.T) string {
	t.Helper()
	dsn := os.Getenv("TEST_DATABASE_URL")
	if dsn == "" {
		t.Fatal("TEST_DATABASE_URL is not set — integration tests require an explicit test database, not a silent skip")
	}
	return dsn
}

// newTestPool runs migrations against a fresh connection to prove the real
// go:embed source (see migrate_test.go rationale), then returns a pooled
// connection for the tests themselves. Per-test isolation comes from the
// setup-time truncate below; t.Cleanup only closes the pool. It must NOT
// truncate: a test may legitimately close the pool itself (see
// TestRepository_AfterPoolClose_ReturnsError), and a cleanup-time truncate
// through an already-closed pool would t.Fatalf. pgxpool.Close is
// idempotent, so a double close from such a test is harmless.
func newTestPool(t *testing.T) *pgxpool.Pool {
	t.Helper()
	dsn := testDSN(t)

	if err := postgres.RunMigrations(dsn); err != nil {
		t.Fatalf("RunMigrations: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("pgxpool.New: %v", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		t.Fatalf("pool.Ping: %v", err)
	}

	t.Cleanup(func() {
		pool.Close()
	})

	truncateBookmarks(t, pool)
	return pool
}

// truncateBookmarks resets table state between tests.
func truncateBookmarks(t *testing.T, pool *pgxpool.Pool) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if _, err := pool.Exec(ctx, "TRUNCATE TABLE bookmarks"); err != nil {
		t.Fatalf("truncateBookmarks: %v", err)
	}
}

// newTestRepository wires a Repository over a fresh pool with a frozen
// clock — see DECISIONS.md "Timestamp source — injectable clock."
func newTestRepository(t *testing.T) (*postgres.Repository, *pgxpool.Pool, time.Time) {
	t.Helper()
	pool := newTestPool(t)
	frozen := time.Date(2026, 7, 9, 12, 0, 0, 0, time.UTC)
	repo := postgres.New(pool, fixedClock(frozen))
	return repo, pool, frozen
}

// fixedClock returns a clock function that always reports t — see
// DECISIONS.md "Timestamp source — injectable clock."
func fixedClock(t time.Time) func() time.Time {
	return func() time.Time { return t }
}

// insertRawBookmark bypasses Repository.Create entirely — used only by
// tests that need to induce a specific raw-SQL condition (e.g. a
// non-identity-hash constraint violation) that Create's own write path
// cannot produce under normal operation, since gen_random_uuid() makes a
// real bookmarks_pkey collision vanishingly improbable through the public
// API. tags is omitted deliberately — ARCHITECTURE_RFC.md "Persistence
// Schema" declares `tags jsonb NOT NULL DEFAULT '[]'::jsonb`, so the
// omission defaults cleanly.
func insertRawBookmark(ctx context.Context, pool *pgxpool.Pool, id, identityHash string) error {
	const q = `
		INSERT INTO bookmarks
			(id, original_url, canonical_url, identity_hash, title, status, position, created_at, updated_at)
		VALUES
			($1, $2, $3, $4, 'raw test row', 'inbox', 'a', now(), now())
	`
	_, err := pool.Exec(ctx, q, id, fmt.Sprintf("https://example.com/%s", identityHash), fmt.Sprintf("https://example.com/%s", identityHash), identityHash)
	return err
}

// insertRawBookmarkAt bypasses Repository.Create and Move entirely,
// giving move_test.go direct control over status and position for
// fixture rows — Move's neighbor-fallback and ordering behavior must be
// provable independent of Create's own position-assignment scheme (see
// DECISIONS.md "Position Collision Handling (Decision B, resolved)").
// tags/author/finished_at are omitted deliberately, same rationale as
// insertRawBookmark above.
func insertRawBookmarkAt(ctx context.Context, pool *pgxpool.Pool, id, identityHash, status, position string) error {
	const q = `
		INSERT INTO bookmarks
			(id, original_url, canonical_url, identity_hash, title, status, position, created_at, updated_at)
		VALUES
			($1, $2, $3, $4, 'raw test row', $5, $6, now(), now())
	`
	_, err := pool.Exec(ctx, q, id, fmt.Sprintf("https://example.com/%s", identityHash), fmt.Sprintf("https://example.com/%s", identityHash), identityHash, status, position)
	return err
}

// testUUID returns a deterministic, validly-shaped UUID string for raw
// fixture rows — bookmarks.id is a native Postgres uuid column, so
// fixture IDs must parse as UUIDs, not arbitrary strings.
func testUUID(n int) string {
	return fmt.Sprintf("00000000-0000-0000-0000-%012d", n)
}

// mutableClock is an advanceable clock for tests that must distinguish
// "timestamp preserved from an earlier instant" from "timestamp
// re-stamped to now" — e.g. the Done→Done Move case (DECISIONS.md
// "FinishedAt <-> Done invariant"). newTestRepository's frozen clock
// can't express this: a single fixed instant can't tell "preserved" and
// "re-stamped to the same instant" apart. Safe for the one test that
// uses it (single goroutine, advanced between two sequential calls) —
// the mutex guards against Repository's own internal usage, not
// concurrent test-side advancement.
type mutableClock struct {
	mu  sync.Mutex
	now time.Time
}

func newMutableClock(start time.Time) *mutableClock {
	return &mutableClock{now: start}
}

func (c *mutableClock) Now() time.Time {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.now
}

func (c *mutableClock) Advance(d time.Duration) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.now = c.now.Add(d)
}
