// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 6 tests
// Interview-generated: 3 tests
// Total: 9 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Component contract: <App /> is the single top-level component (design.md
// "Navigation: none — the app is one view") — it fetches GET /api/board on
// mount, renders the header (h1 "Trailhead" wordmark + <AddBar/>) and the
// three columns (h2 per column, a labelled list per column, a listitem per
// card — design.md Accessibility Baseline), and wraps the board in
// dnd-kit's <DndContext> (drag *behavior* is Playwright's job per the
// two-layer test strategy — this file only proves the aria-live wiring
// dnd-kit needs is present, not the announcement text of a real drag).
// Loading state: a skeleton per column (data-testid="column-skeleton"),
// per design.md "Loading states". Error state / empty-state copy is
// exact per design.md "Error states" / "Empty states".

import { delay, http, HttpResponse } from 'msw';
import { describe, expect, it } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { App } from './App';
import { errorHandlers, makeBookmark } from './mocks/handlers';
import { server } from './mocks/server';
import type { Board } from './api/types';

describe('App', () => {
  // --- Auto-generated: loading/board/error/empty states (UI Contract) ---

  it('shows a per-column loading skeleton while GET /api/board is in flight, then removes it once it resolves', async () => {
    server.use(
      http.get('/api/board', async () => {
        await delay(50);
        return HttpResponse.json({ inbox: [], reading: [], done: [] } satisfies Board);
      }),
    );
    render(<App />);

    expect(screen.getAllByTestId('column-skeleton')).toHaveLength(3);
    await waitFor(() => expect(screen.queryAllByTestId('column-skeleton')).toHaveLength(0));
  });

  it('renders the h1 wordmark and one h2 per column in Inbox/Reading/Done order', async () => {
    render(<App />);
    expect(await screen.findByRole('heading', { level: 1, name: 'Trailhead' })).toBeInTheDocument();
    const h2s = await screen.findAllByRole('heading', { level: 2 });
    expect(h2s.map((h) => h.textContent)).toEqual(['Inbox', 'Reading', 'Done']);
  });

  it('renders each column as a list labelled by its column name, with a listitem per card', async () => {
    const board: Board = {
      inbox: [makeBookmark({ id: 'i1', title: 'Inbox Item' })],
      reading: [],
      done: [],
    };
    server.use(errorHandlers.boardOk(board));
    render(<App />);

    const inboxList = await screen.findByRole('list', { name: 'Inbox' });
    expect(screen.getByRole('listitem', { name: /inbox item/i })).toBeInTheDocument();
    expect(inboxList).toContainElement(screen.getByRole('listitem', { name: /inbox item/i }));
  });

  it('given the board fails to load (500), shows the page-level error message with a "Try again" button, which retries the fetch on click', async () => {
    server.use(errorHandlers.boardInternalError());
    const user = userEvent.setup();
    render(<App />);

    expect(
      await screen.findByText("Couldn't load your board. Check your connection and try again."),
    ).toBeInTheDocument();
    const retry = screen.getByRole('button', { name: /try again/i });

    server.use(errorHandlers.boardOk({ inbox: [], reading: [], done: [] }));
    await user.click(retry);

    expect(await screen.findAllByRole('heading', { level: 2 })).toHaveLength(3);
  });

  it('renders each column\'s designed empty-state copy when that column has no bookmarks', async () => {
    server.use(errorHandlers.boardOk({ inbox: [], reading: [], done: [] }));
    render(<App />);

    expect(await screen.findByText('Nothing saved yet. Paste a link above to start your board.')).toBeInTheDocument();
    expect(screen.getByText('Drag a card here when you start reading it.')).toBeInTheDocument();
    expect(screen.getByText('Finished something? Drag it here to check it off.')).toBeInTheDocument();
  });

  it('renders no empty-state copy for a column that has bookmarks', async () => {
    server.use(
      errorHandlers.boardOk({
        inbox: [makeBookmark({ id: 'i1' })],
        reading: [],
        done: [],
      }),
    );
    render(<App />);
    await screen.findByRole('list', { name: 'Inbox' });
    expect(screen.queryByText('Nothing saved yet. Paste a link above to start your board.')).not.toBeInTheDocument();
  });

  // --- Interview-generated ---

  // from interview: Q7 (external dependencies controlled in tests) — the
  // aria-live region dnd-kit's DndContext needs for drag announcements
  // must be present in the DOM as soon as the board renders, not created
  // lazily on first drag (a screen reader must already be tracking the
  // region before the first announcement fires, or that first
  // announcement is silently lost).
  it('renders a status/aria-live region for drag announcements once the board has loaded', async () => {
    render(<App />);
    await screen.findAllByRole('heading', { level: 2 });
    expect(screen.getByRole('status')).toBeInTheDocument();
  });

  // from interview: Q3 (most likely silent-failure mode) — an
  // empty-state check written against "is the whole board empty" instead
  // of "is this column empty" would silently pass every test above (each
  // uses a uniformly-empty or uniformly-populated board) and only fail on
  // a mixed board — exactly the shape a real user's board usually has.
  it('shows Inbox\'s empty state even when Reading and Done both have cards', async () => {
    server.use(
      errorHandlers.boardOk({
        inbox: [],
        reading: [makeBookmark({ id: 'r1', status: 'reading' })],
        done: [makeBookmark({ id: 'd1', status: 'done', finished_at: '2026-08-01T00:00:00Z' })],
      }),
    );
    render(<App />);

    expect(await screen.findByText('Nothing saved yet. Paste a link above to start your board.')).toBeInTheDocument();
    expect(screen.queryByText('Drag a card here when you start reading it.')).not.toBeInTheDocument();
    expect(screen.queryByText('Finished something? Drag it here to check it off.')).not.toBeInTheDocument();
  });

  // from interview: Q1 — the error state's recovery path (design.md "No
  // dead ends") must itself be keyboard-operable, not just clickable.
  it('the "Try again" button is keyboard-operable (Enter triggers retry)', async () => {
    server.use(errorHandlers.boardInternalError());
    const user = userEvent.setup();
    render(<App />);

    const retry = await screen.findByRole('button', { name: /try again/i });
    retry.focus();

    server.use(errorHandlers.boardOk({ inbox: [], reading: [], done: [] }));
    await user.keyboard('{Enter}');

    expect(await screen.findAllByRole('heading', { level: 2 })).toHaveLength(3);
  });
});
