// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 6 tests
// Interview-generated: 5 tests
// Total: 11 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Locks the Add bar half of the UI Contract in
// docs/issues/06-frontend-board-add-bar.md — component contract:
//   <AddBar onCreated={(bookmark) => void} onTransientError={(message: string) => void} />
// AddBar owns POST /api/bookmarks and every inline (400/409) error
// presentation itself; it never touches board state directly. On success
// it calls onCreated with the created domain.Bookmark (App patches local
// state from that value — no GET /api/board refetch, see UI Contract
// "Add bar optimism: no card until 201"). On a transient failure
// (413/500) it calls onTransientError so the App-level toast can show it
// — AddBar renders no toast of its own.
//
// Copy is exact per design.md "Inputs" / "Error states" where design.md
// gives it verbatim; the empty-input (`bad_request`) and transient-error
// (413/500) strings are Pre-Phase F additions that were NOT given verbatim
// in design.md — written to match its locked message-format rule ("says
// what happened AND what to do next") and flagged here for the developer
// to confirm/amend at approval, same as any other Pre-Phase F copy gap.

import { delay, http, HttpResponse } from 'msw';
import { describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { AddBar } from './AddBar';
import { errorHandlers, makeBookmark } from '../mocks/handlers';
import { server } from '../mocks/server';

describe('AddBar', () => {
  // --- Auto-generated: DOM/accessibility contract + happy path (UI Contract) ---

  it('renders a labelled textbox with the locked placeholder text', () => {
    render(<AddBar onCreated={vi.fn()} onTransientError={vi.fn()} />);
    const input = screen.getByRole('textbox', { name: /add a bookmark by url/i });
    expect(input).toHaveAttribute('placeholder', 'Paste a link to save it…');
  });

  it('renders the input inside a <form> with a submit button', () => {
    render(<AddBar onCreated={vi.fn()} onTransientError={vi.fn()} />);
    const input = screen.getByRole('textbox', { name: /add a bookmark by url/i });
    expect(input.closest('form')).not.toBeNull();
    expect(screen.getByRole('button', { name: /save/i })).toHaveAttribute('type', 'submit');
  });

  it('given a valid URL, submitting calls onCreated with the created bookmark and clears the input', async () => {
    const user = userEvent.setup();
    const onCreated = vi.fn();
    render(<AddBar onCreated={onCreated} onTransientError={vi.fn()} />);

    const input = screen.getByRole('textbox', { name: /add a bookmark by url/i });
    await user.type(input, 'https://example.com/article');
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => expect(onCreated).toHaveBeenCalledTimes(1));
    expect(onCreated.mock.calls[0][0]).toMatchObject({ original_url: 'https://example.com/article' });
    expect(input).toHaveValue('');
  });

  it('given a duplicate URL (409), shows the inline duplicate message with a link to the existing card, and does not call onCreated', async () => {
    const existing = makeBookmark({ id: 'existing-id', original_url: 'https://example.com/already-saved' });
    server.use(errorHandlers.createDuplicate(existing));

    const user = userEvent.setup();
    const onCreated = vi.fn();
    render(<AddBar onCreated={onCreated} onTransientError={vi.fn()} />);

    await user.type(screen.getByRole('textbox', { name: /add a bookmark by url/i }), 'https://example.com/already-saved');
    await user.click(screen.getByRole('button', { name: /save/i }));

    await screen.findByText('This is already on your board.');
    const link = screen.getByRole('link', { name: /show it/i });
    expect(link).toHaveAttribute('href', '#bookmark-existing-id');
    expect(onCreated).not.toHaveBeenCalled();
  });

  it('given an invalid URL (400 invalid_url), shows "That doesn\'t look like a web address." and does not call onCreated', async () => {
    server.use(errorHandlers.createInvalidUrl());

    const user = userEvent.setup();
    const onCreated = vi.fn();
    render(<AddBar onCreated={onCreated} onTransientError={vi.fn()} />);

    await user.type(screen.getByRole('textbox', { name: /add a bookmark by url/i }), 'not a url');
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(await screen.findByText("That doesn't look like a web address.")).toBeInTheDocument();
    expect(onCreated).not.toHaveBeenCalled();
  });

  it('given a 500 response, calls onTransientError and does not render an inline field message', async () => {
    server.use(errorHandlers.createInternalError());

    const user = userEvent.setup();
    const onTransientError = vi.fn();
    render(<AddBar onCreated={vi.fn()} onTransientError={onTransientError} />);

    await user.type(screen.getByRole('textbox', { name: /add a bookmark by url/i }), 'https://example.com/article');
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => expect(onTransientError).toHaveBeenCalledTimes(1));
    expect(onTransientError.mock.calls[0][0]).toEqual(expect.stringContaining('Try again'));
    expect(screen.queryByText(/web address|already on your board/i)).not.toBeInTheDocument();
  });

  // --- Interview-generated ---

  // from interview: Q1 (conditions the AC doesn't explicitly describe) —
  // 413 is grouped with 500 by the issue text ("on 413/500, a toast");
  // lock it as its own case so the two aren't accidentally conflated into
  // one untested code path.
  it('given a 413 response, calls onTransientError the same way as a 500', async () => {
    server.use(errorHandlers.createPayloadTooLarge());

    const user = userEvent.setup();
    const onTransientError = vi.fn();
    render(<AddBar onCreated={vi.fn()} onTransientError={onTransientError} />);

    await user.type(screen.getByRole('textbox', { name: /add a bookmark by url/i }), 'https://example.com/article');
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => expect(onTransientError).toHaveBeenCalledTimes(1));
  });

  // from interview: Q1 — web-design-guidelines "Submit is not
  // pre-disabled": an empty submit must be allowed through to surface
  // validation feedback, not silently blocked by a disabled button.
  it('given an empty input, submitting is allowed (button is not pre-disabled) and shows an inline message from the bad_request response', async () => {
    server.use(errorHandlers.createBadRequest('url is required'));

    const user = userEvent.setup();
    const onCreated = vi.fn();
    render(<AddBar onCreated={onCreated} onTransientError={vi.fn()} />);

    expect(screen.getByRole('button', { name: /save/i })).toBeEnabled();
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(await screen.findByText('Paste a link before saving.')).toBeInTheDocument();
    expect(onCreated).not.toHaveBeenCalled();
  });

  // from interview: Q1 — the in-flight state between submit and response,
  // which the acceptance criteria don't cover directly but design.md's
  // "…" ellipsis convention and the optimistic-UI note both imply.
  it('shows a loading state on the submit button while the create request is in flight', async () => {
    server.use(
      http.post('/api/bookmarks', async () => {
        await delay(50);
        return HttpResponse.json(makeBookmark({ original_url: 'https://example.com/slow' }), { status: 201 });
      }),
    );

    const user = userEvent.setup();
    render(<AddBar onCreated={vi.fn()} onTransientError={vi.fn()} />);

    await user.type(screen.getByRole('textbox', { name: /add a bookmark by url/i }), 'https://example.com/slow');
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(screen.getByRole('button', { name: /saving…/i })).toBeDisabled();
    await waitFor(() => expect(screen.getByRole('button', { name: /save/i })).toBeEnabled());
  });

  // from interview: Q3 (most likely silent-failure mode) — an inline
  // error rendered with no programmatic association to the input is
  // invisible to screen-reader users even though sighted users see it;
  // web-design-guidelines Checklist 1 requires aria-live/aria-describedby.
  it('associates the inline error message with the input via aria-describedby when an error is shown', async () => {
    server.use(errorHandlers.createInvalidUrl());

    const user = userEvent.setup();
    render(<AddBar onCreated={vi.fn()} onTransientError={vi.fn()} />);

    const input = screen.getByRole('textbox', { name: /add a bookmark by url/i });
    await user.type(input, 'not a url');
    await user.click(screen.getByRole('button', { name: /save/i }));

    const message = await screen.findByText("That doesn't look like a web address.");
    const describedBy = input.getAttribute('aria-describedby');
    expect(describedBy).toBeTruthy();
    expect(document.getElementById(describedBy!)).toBe(message);
    expect(input).toHaveAttribute('aria-invalid', 'true');
  });

  // from interview: Q1 — keyboard-only submission (Enter inside the
  // input) must work without requiring a pointer click on the button, per
  // the UI Contract's "All of the above are operable by keyboard" AC.
  it('submitting via Enter inside the input (no button click) calls onCreated', async () => {
    const user = userEvent.setup();
    const onCreated = vi.fn();
    render(<AddBar onCreated={onCreated} onTransientError={vi.fn()} />);

    const input = screen.getByRole('textbox', { name: /add a bookmark by url/i });
    await user.type(input, 'https://example.com/keyboard{Enter}');

    await waitFor(() => expect(onCreated).toHaveBeenCalledTimes(1));
  });
});
