// Code generated by test-engine skill on 2026-08-06
// Issue: #6 — Frontend: Board & Add Bar
// Blast radius tier: 2
// Auto-generated: 5 tests
// Interview-generated: 2 tests
// Total: 7 tests
//
// This file was approved by the developer before any code was written.
// The code session that implements this issue may NOT modify this file.
// Changes require re-running the test-engine skill and re-approval.
//
// Component contract: <Card bookmark={domain.Bookmark} /> — a pure
// presentational component, no data fetching of its own. Per UI Contract:
// title links to bookmark.original_url (not canonical_url — the saved
// page, not the dedup key); a host/domain line derived from original_url;
// tag pills (each carries data-testid="tag-pill" — tags have no locked
// list/landmark semantics of their own per design.md Accessibility
// Baseline, so a test id is the stable query here rather than an invented
// ARIA role); a "finished {date}" line only when bookmark.status ===
// 'done' (UTC-explicit formatting — see UI Contract "finished-date
// formatting", avoiding the TZ-dependent-test class already scarred once
// on this project, trailhead-rules Rule 3 / FakeBookmarkRepository's UTC
// clock fix); no status label anywhere on the card (the column conveys
// status — design.md Cards). The rendered root carries
// id={"bookmark-" + id} so the Add bar's duplicate-message link
// (#bookmark-{id}) has a target.

import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';

import { Card } from './Card';
import type { Bookmark } from '../api/types';

function bookmark(overrides: Partial<Bookmark> = {}): Bookmark {
  return {
    id: 'card-1',
    original_url: 'https://example.com/deep/path-to-article',
    canonical_url: 'https://example.com/deep/path-to-article',
    identity_hash: 'hash',
    title: 'A Great Article',
    tags: [],
    status: 'inbox',
    position: '00000000',
    finished_at: null,
    author: null,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    ...overrides,
  };
}

describe('Card', () => {
  // --- Auto-generated: Card contents (UI Contract / design.md "Cards") ---

  it("renders the title as a link to the bookmark's original_url", () => {
    render(<Card bookmark={bookmark({ title: 'A Great Article', original_url: 'https://example.com/x' })} />);
    const link = screen.getByRole('link', { name: 'A Great Article' });
    expect(link).toHaveAttribute('href', 'https://example.com/x');
  });

  it('renders the host/domain line derived from original_url', () => {
    render(<Card bookmark={bookmark({ original_url: 'https://example.com/deep/path' })} />);
    expect(screen.getByText('example.com')).toBeInTheDocument();
  });

  it('renders a pill for every tag', () => {
    render(<Card bookmark={bookmark({ tags: ['reading-list', 'longform'] })} />);
    const pills = screen.getAllByTestId('tag-pill').map((el) => el.textContent);
    expect(pills).toEqual(['reading-list', 'longform']);
  });

  it('renders no tag pills when tags is empty', () => {
    render(<Card bookmark={bookmark({ tags: [] })} />);
    expect(screen.queryAllByTestId('tag-pill')).toHaveLength(0);
  });

  it('renders a "finished {date}" line, UTC-formatted, only for a Done card', () => {
    render(<Card bookmark={bookmark({ status: 'done', finished_at: '2026-08-06T12:00:00Z' })} />);
    expect(screen.getByText('finished Aug 6, 2026')).toBeInTheDocument();
  });

  // --- Interview-generated ---

  // from interview: Q1 — the negative case for the above: a non-Done card
  // must render no finished-date line at all, not an empty one.
  it('renders no "finished" line for a non-Done card', () => {
    render(<Card bookmark={bookmark({ status: 'reading', finished_at: null })} />);
    expect(screen.queryByText(/^finished /)).not.toBeInTheDocument();
  });

  // from interview: Q3 (most likely silent-failure mode) — design.md:
  // "No status label on the card — the column conveys status." A
  // regression here is silent (the card still renders, just with an extra
  // word) so it needs its own explicit test, not an incidental one.
  it('does not render the raw status word anywhere on the card', () => {
    const { container } = render(<Card bookmark={bookmark({ status: 'reading' })} />);
    expect(container.textContent).not.toMatch(/\breading\b/i);
  });
});
